import { useState } from 'react';
import { Plus, Trash2, WalletCards } from 'lucide-react';
import { UserSettings } from '../types';

const suggestions=['IOL','Binance','Balanz','Cocos Capital','Bull Market','InvertirOnline','Mercado Pago','Ualá','Ripio','Buenbit','Lemon','eToro','Interactive Brokers'];
type Balance={name:string;value:number;source?:'manual'|'iol'};
export default function InvestmentPreferences({settings,onChange,balances=[]}:{settings:UserSettings;onChange:(settings:UserSettings)=>void;balances?:Balance[]}) {
  const [name,setName]=useState(''),[error,setError]=useState('');const platforms=settings.investmentPlatforms||[],overrides=settings.investmentBalanceOverrides||{};
  const add=(value=name)=>{const clean=value.trim();if(!clean||platforms.some(item=>item.toLowerCase()===clean.toLowerCase())){setError(clean?'Esa plataforma ya está agregada.':'Ingresá el nombre de una plataforma.');return}onChange({...settings,investmentPlatforms:[...platforms,clean]});setName('');setError('')};
  const balanceFor=(platform:string)=>{const overridden=Object.entries(overrides).find(([item])=>item.toLowerCase()===platform.toLowerCase())?.[1];return Number.isFinite(overridden)?Number(overridden):balances.find(item=>item.name.toLowerCase()===platform.toLowerCase())?.value||0};
  const updateBalance=(platform:string,value:string)=>onChange({...settings,investmentBalanceOverrides:{...overrides,[platform]:Math.max(0,Number(value)||0)}});
  return <div className="gefi-setting-stack"><section className="gefi-setting-card"><div className="gefi-setting-card-head"><WalletCards/><div><h3>Plataformas de inversión</h3><p>Elegí las aplicaciones que usás. Se mostrarán al registrar y consultar inversiones.</p></div></div><div className="gefi-setting-inline-form"><input value={name} onChange={event=>{setName(event.target.value);setError('')}} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();add()}}} list="investment-platform-suggestions" placeholder="Ej: Lemon" className="gefi-setting-input"/><datalist id="investment-platform-suggestions">{suggestions.map(item=><option key={item} value={item}/>)}</datalist><button type="button" onClick={()=>add()}><Plus/>Agregar</button></div>{error&&<p className="gefi-settings-feedback error">{error}</p>}<div className="gefi-setting-tags">{platforms.length?platforms.map(item=><span key={item}>{item}<button type="button" onClick={()=>onChange({...settings,investmentPlatforms:platforms.filter(platform=>platform!==item)})} aria-label={`Eliminar ${item}`}><Trash2/></button></span>):<p className="text-xs text-slate-400">Agregá al menos una plataforma para clasificar tus próximas inversiones.</p>}</div></section><section className="gefi-setting-card"><div className="gefi-setting-card-head"><WalletCards/><div><h3>Saldo por plataforma</h3><p>Corregí el importe real sin crear un gasto, ingreso ni transferencia.</p></div></div><div className="gefi-investment-balances">{platforms.length?platforms.map(platform=>{const live=balances.find(item=>item.name.toLowerCase()===platform.toLowerCase())?.source==='iol';return <label key={platform}><span><strong>{platform}</strong><small>{live?'Sincronizado automáticamente':'Saldo invertido actual'}</small></span><input aria-label={`Saldo invertido en ${platform}`} type="number" min="0" step="any" inputMode="decimal" value={balanceFor(platform)} disabled={live} onChange={event=>updateBalance(platform,event.target.value)} className="gefi-setting-input"/></label>}):<p className="text-xs text-slate-400">Agregá una plataforma para corregir su saldo.</p>}</div></section></div>;
}
