import { useState } from 'react';
import { Plus, Trash2, WalletCards } from 'lucide-react';
import { UserSettings } from '../types';

const suggestions=['IOL','Binance','Balanz','Cocos Capital','Bull Market','InvertirOnline','Mercado Pago','Ualá','Ripio','Buenbit','eToro','Interactive Brokers'];
export default function InvestmentPreferences({settings,onChange}:{settings:UserSettings;onChange:(settings:UserSettings)=>void}) {
  const [name,setName]=useState(''),[error,setError]=useState('');const platforms=settings.investmentPlatforms||[];
  const add=(value=name)=>{const clean=value.trim();if(!clean||platforms.some(item=>item.toLowerCase()===clean.toLowerCase())){setError(clean?'Esa plataforma ya está agregada.':'Ingresá el nombre de una plataforma.');return}onChange({...settings,investmentPlatforms:[...platforms,clean]});setName('');setError('')};
  return <section className="mt-6 rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex items-start gap-2"><WalletCards className="mt-0.5 h-4 w-4 text-blue-600"/><div><h3 className="text-sm font-bold">Plataformas de inversión</h3><p className="mt-1 text-[10px] text-slate-400">Elegí las aplicaciones que usás. Se mostrarán al registrar y consultar inversiones.</p></div></div><div className="mt-3 flex gap-2"><input value={name} onChange={event=>{setName(event.target.value);setError('')}} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();add()}}} list="investment-platform-suggestions" placeholder="Ej: Balanz" className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-slate-50 p-2.5 text-xs dark:border-slate-700 dark:bg-slate-950"/><datalist id="investment-platform-suggestions">{suggestions.map(item=><option key={item} value={item}/>)}</datalist><button type="button" onClick={()=>add()} className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 text-xs font-bold text-white"><Plus className="h-3.5 w-3.5"/>Agregar</button></div>{error&&<p className="mt-2 text-[10px] text-rose-600">{error}</p>}<div className="mt-3 flex flex-wrap gap-2">{platforms.length?platforms.map(item=><span key={item} className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1.5 text-xs dark:bg-slate-800">{item}<button type="button" onClick={()=>onChange({...settings,investmentPlatforms:platforms.filter(platform=>platform!==item)})} aria-label={`Eliminar ${item}`} className="text-slate-400 hover:text-rose-600"><Trash2 className="h-3 w-3"/></button></span>):<p className="text-xs text-slate-400">Agregá al menos una plataforma para clasificar tus próximas inversiones.</p>}</div></section>;
}
