import { useEffect, useMemo, useState } from 'react';
import { Accessibility, ArchiveRestore, Bell, ChevronRight, Database, Download, ExternalLink, HandCoins, Landmark, Link, Plus, Settings, SlidersHorizontal, Tags, Trash2, WalletCards, X } from 'lucide-react';
import { Account, FixedExpense, Loan, Transaction, UserSettings } from '../types';
import { applyLanguage } from '../i18n';
import AccessibilityPanel from './AccessibilityPanel';
import InvestmentPreferences from './InvestmentPreferences';

type CorrectionKind='accounts'|'cash'|'patrimony'|'investment';
type SectionId='preferences'|'investments'|'categories'|'accounts'|'loans'|'links'|'trash'|'accessibility'|'backup';
type Props={settings:UserSettings;accounts:Account[];fixed?:FixedExpense[];loans:Loan[];trashedTxs:Transaction[];correctionValues:Record<CorrectionKind,number>;onCorrectBalance:(kind:CorrectionKind,target:number)=>Promise<void>;onRestoreTx:(id:string)=>Promise<void>;onPermanentlyDeleteTx:(id:string)=>Promise<void>;onClose:()=>void;onSave:(settings:UserSettings)=>Promise<void>;onExport:()=>void;onImport:(file:File)=>Promise<void>;onAddAccount:(data?:{nombre:string;tipo:Account['tipo'];saldoInicial:number})=>Promise<void>;onDeleteAccount:(id:string)=>Promise<void>;onAddLoan:(data?:{persona:string;monto:number;motivo:string;cuentaId:string})=>Promise<void>};

const sections:Array<{id:SectionId;group:string;title:string;description:string;icon:typeof Settings}>=[
 {id:'preferences',group:'Personalización',title:'Preferencias',description:'Idioma, moneda y avisos',icon:SlidersHorizontal},
 {id:'investments',group:'Personalización',title:'Inversiones',description:'Plataformas que utilizás',icon:WalletCards},
 {id:'categories',group:'Organización',title:'Categorías',description:'Clasificación de gastos',icon:Tags},
 {id:'accounts',group:'Organización',title:'Cuentas y saldos',description:'Cuentas, efectivo y correcciones',icon:Landmark},
 {id:'loans',group:'Organización',title:'Préstamos',description:'Personas y deudas',icon:HandCoins},
 {id:'links',group:'Organización',title:'Accesos directos',description:'Tus enlaces frecuentes',icon:Link},
 {id:'trash',group:'Datos',title:'Papelera',description:'Movimientos eliminados',icon:ArchiveRestore},
 {id:'accessibility',group:'Datos',title:'Accesibilidad',description:'Tamaño y legibilidad',icon:Accessibility},
 {id:'backup',group:'Datos',title:'Respaldo',description:'Exportar o recuperar datos',icon:Database},
];
const normalizeUrl=(raw:string)=>{try{const value=/^https?:\/\//i.test(raw.trim())?raw.trim():`https://${raw.trim()}`;const parsed=new URL(value);return /^https?:$/.test(parsed.protocol)?parsed.toString():''}catch{return ''}};
const money=(value:number,currency:string)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:currency||'ARS'}).format(value||0);

export default function ModernSettingsPanel(props:Props){
 const {settings,accounts,loans,trashedTxs,correctionValues,onCorrectBalance,onRestoreTx,onPermanentlyDeleteTx,onClose,onSave,onExport,onImport,onAddAccount,onDeleteAccount,onAddLoan}=props;
 const [draft,setDraft]=useState(settings),[active,setActive]=useState<SectionId>('preferences'),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [newCategory,setNewCategory]=useState(''),[accountForm,setAccountForm]=useState(false),[accountDraft,setAccountDraft]=useState({nombre:'',tipo:'Banco' as Account['tipo'],saldoInicial:0});
 const [linkForm,setLinkForm]=useState(false),[linkDraft,setLinkDraft]=useState({nombre:'',url:''}),[loanForm,setLoanForm]=useState(false),[loanDraft,setLoanDraft]=useState({persona:'',monto:0,motivo:'',cuentaId:''});
 const [correctionKind,setCorrectionKind]=useState<CorrectionKind>('accounts'),[correctionTarget,setCorrectionTarget]=useState(String(correctionValues.accounts)),[deleteAccount,setDeleteAccount]=useState<Account|null>(null),[deleteTrash,setDeleteTrash]=useState<Transaction|null>(null),[importFile,setImportFile]=useState<File|null>(null);
 const current=useMemo(()=>sections.find(item=>item.id===active)!,[active]);
 useEffect(()=>{if(draft.language==='en')return applyLanguage('en',false);if(settings.language==='en')return applyLanguage('es',false)},[draft.language,settings.language]);
 const open=(id:SectionId)=>{setActive(id);setError('');setNotice('')};
 const save=async()=>{setSaving(true);setError('');try{await onSave(draft);onClose()}catch{setError('No se pudo guardar la configuración. Intentá nuevamente.')}finally{setSaving(false)}};
 const addCategory=()=>{const value=newCategory.trim();if(!value||draft.categorias.some(item=>item.toLowerCase()===value.toLowerCase()))return;setDraft({...draft,categorias:[...draft.categorias,value]});setNewCategory('')};
 const createAccount=async()=>{if(!accountDraft.nombre.trim()||accountDraft.saldoInicial<0){setError('Ingresá un nombre y un saldo inicial válido.');return}setSaving(true);try{await onAddAccount({...accountDraft,nombre:accountDraft.nombre.trim()});setAccountDraft({nombre:'',tipo:'Banco',saldoInicial:0});setAccountForm(false);setNotice('Cuenta agregada correctamente.')}finally{setSaving(false)}};
 const createLoan=async()=>{if(!loanDraft.persona.trim()||loanDraft.monto<=0){setError('Ingresá una persona y un importe mayor que cero.');return}setSaving(true);try{await onAddLoan({...loanDraft,persona:loanDraft.persona.trim()});setLoanDraft({persona:'',monto:0,motivo:'',cuentaId:''});setLoanForm(false);setNotice('Préstamo agregado correctamente.')}finally{setSaving(false)}};
 const addLink=()=>{const url=normalizeUrl(linkDraft.url);if(!url){setError('Ingresá una URL válida. El nombre es opcional.');return}setDraft({...draft,quickLinks:[...draft.quickLinks,{id:crypto.randomUUID(),nombre:linkDraft.nombre.trim().slice(0,100),url}]});setLinkDraft({nombre:'',url:''});setLinkForm(false)};
 const applyCorrection=async()=>{const target=Number(correctionTarget);if(!Number.isFinite(target)){setError('Ingresá un importe válido.');return}if(Math.abs(target-correctionValues[correctionKind])<.01){setError('El nuevo importe es igual al saldo actual.');return}setSaving(true);try{await onCorrectBalance(correctionKind,target);setNotice('Saldo corregido correctamente.')}finally{setSaving(false)}};
 const input='gefi-setting-input';
 const sectionContent=()=>{
  if(active==='preferences')return <div className="gefi-setting-stack"><div className="gefi-setting-card"><div className="gefi-setting-card-head"><SlidersHorizontal/><div><h3>Preferencias regionales</h3><p>Definí cómo se muestran los importes y el idioma de la aplicación.</p></div></div><div className="gefi-setting-grid"><label>Moneda principal<select value={draft.monedaBase} onChange={event=>setDraft({...draft,monedaBase:event.target.value})} className={input}>{draft.monedas.map(code=><option key={code}>{code}</option>)}</select></label><label>Idioma<select value={draft.language||'es'} onChange={event=>setDraft({...draft,language:event.target.value as 'es'|'en'})} className={input}><option value="es">Español</option><option value="en">English</option></select></label></div></div><div className="gefi-setting-card"><div className="gefi-setting-card-head"><Bell/><div><h3>Contenido y avisos</h3><p>Elegí qué información querés ver y recibir.</p></div></div><SettingToggle title="Sección de ahorros" description="Mostrar tus ahorros en el resumen principal." checked={draft.showSavings!==false} onChange={checked=>setDraft({...draft,showSavings:checked})}/><SettingToggle title="Resumen mensual" description="Balance del mes, comienzo del nuevo período y un consejo financiero." checked={draft.monthlyEmailSummary!==false} onChange={checked=>setDraft({...draft,monthlyEmailSummary:checked})}/><SettingToggle title="Recordatorios de pagos" description="Avisos antes del vencimiento, el mismo día y cuando haya vencido." checked={draft.paymentEmailReminders!==false} onChange={checked=>setDraft({...draft,paymentEmailReminders:checked})}/></div></div>;
  if(active==='investments')return <div className="gefi-setting-component"><InvestmentPreferences settings={draft} onChange={setDraft}/></div>;
  if(active==='categories')return <div className="gefi-setting-card"><div className="gefi-setting-card-head"><Tags/><div><h3>Categorías de gasto</h3><p>Creá categorías claras para entender en qué utilizás tu dinero.</p></div></div><div className="gefi-setting-inline-form"><input value={newCategory} onChange={event=>setNewCategory(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();addCategory()}}} placeholder="Nombre de la categoría" className={input}/><button type="button" onClick={addCategory}><Plus/>Agregar</button></div><div className="gefi-setting-tags">{draft.categorias.map(category=><span key={category}>{category}<button type="button" onClick={()=>setDraft({...draft,categorias:draft.categorias.filter(item=>item!==category)})} aria-label={`Eliminar ${category}`}><X/></button></span>)}</div></div>;
  if(active==='accounts')return <div className="gefi-setting-stack"><div className="gefi-setting-card"><div className="gefi-setting-card-head"><Landmark/><div><h3>Cuentas y efectivo</h3><p>Administrá los lugares donde guardás tu dinero.</p></div><button className="gefi-setting-text-action" onClick={()=>setAccountForm(true)}>Agregar cuenta</button></div>{accountForm&&<div className="gefi-setting-form"><input autoFocus value={accountDraft.nombre} onChange={event=>setAccountDraft({...accountDraft,nombre:event.target.value})} placeholder="Nombre de la cuenta" className={input}/><select value={accountDraft.tipo} onChange={event=>setAccountDraft({...accountDraft,tipo:event.target.value as Account['tipo']})} className={input}><option>Banco</option><option>Billetera</option><option>Efectivo</option></select><input type="number" min="0" value={accountDraft.saldoInicial} onChange={event=>setAccountDraft({...accountDraft,saldoInicial:Number(event.target.value)})} placeholder="Saldo inicial" className={input}/><div><button className="secondary" onClick={()=>setAccountForm(false)}>Cancelar</button><button onClick={createAccount}>Guardar cuenta</button></div></div>}<div className="gefi-setting-list">{accounts.length?accounts.map(account=><article key={account.id}><span className="gefi-setting-list-icon"><Landmark/></span><div><strong>{account.nombre}</strong><small>{account.tipo} · {account.moneda}</small></div><button className="danger" onClick={()=>setDeleteAccount(account)} aria-label={`Eliminar ${account.nombre}`}><Trash2/></button></article>):<Empty text="Todavía no agregaste ninguna cuenta."/>}</div></div><div className="gefi-setting-card correction"><div className="gefi-setting-card-head"><Settings/><div><h3>Corrección de saldos</h3><p>Ajustá un total cuando no coincida con la realidad. La diferencia queda registrada.</p></div></div><div className="gefi-setting-grid"><label>Saldo a corregir<select value={correctionKind} onChange={event=>{const kind=event.target.value as CorrectionKind;setCorrectionKind(kind);setCorrectionTarget(String(correctionValues[kind]))}} className={input}><option value="accounts">Dinero en cuenta</option><option value="cash">Efectivo</option><option value="patrimony">Patrimonio total</option><option value="investment">Inversiones</option></select></label><label>Nuevo importe<input type="number" step="any" value={correctionTarget} onChange={event=>setCorrectionTarget(event.target.value)} className={input}/></label></div><div className="gefi-correction-summary"><span>Saldo actual<strong>{money(correctionValues[correctionKind],draft.monedaBase)}</strong></span><button disabled={saving} onClick={applyCorrection}>Aplicar corrección</button></div></div></div>;
  if(active==='loans')return <div className="gefi-setting-card"><div className="gefi-setting-card-head"><HandCoins/><div><h3>Préstamos realizados</h3><p>Registrá dinero prestado y consultá cada deuda pendiente.</p></div><button className="gefi-setting-text-action" onClick={()=>setLoanForm(true)}>Nuevo préstamo</button></div>{loanForm&&<div className="gefi-setting-form two"><input autoFocus value={loanDraft.persona} onChange={event=>setLoanDraft({...loanDraft,persona:event.target.value})} placeholder="Nombre de la persona" className={input}/><input type="number" min=".01" value={loanDraft.monto} onChange={event=>setLoanDraft({...loanDraft,monto:Number(event.target.value)})} placeholder="Importe" className={input}/><input value={loanDraft.motivo} onChange={event=>setLoanDraft({...loanDraft,motivo:event.target.value})} placeholder="Motivo opcional" className={input}/><select value={loanDraft.cuentaId} onChange={event=>setLoanDraft({...loanDraft,cuentaId:event.target.value})} className={input}><option value="">Sin cuenta</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.nombre}</option>)}</select><div><button className="secondary" onClick={()=>setLoanForm(false)}>Cancelar</button><button onClick={createLoan}>Guardar préstamo</button></div></div>}<div className="gefi-setting-list">{loans.length?loans.map(loan=><article key={loan.id}><span className="gefi-setting-list-icon"><HandCoins/></span><div><strong>{loan.persona}</strong><small>{loan.motivo||'Sin detalle'} · {loan.estado}</small></div><b>{money(loan.monto,loan.moneda||draft.monedaBase)}</b></article>):<Empty text="No hay préstamos registrados."/>}</div></div>;
  if(active==='links')return <div className="gefi-setting-card"><div className="gefi-setting-card-head"><Link/><div><h3>Accesos directos</h3><p>Guardá sitios frecuentes. Solo la dirección web es obligatoria.</p></div><button className="gefi-setting-text-action" onClick={()=>setLinkForm(true)}>Agregar acceso</button></div>{linkForm&&<div className="gefi-setting-form two"><input value={linkDraft.nombre} onChange={event=>setLinkDraft({...linkDraft,nombre:event.target.value})} placeholder="Nombre opcional" className={input}/><input autoFocus value={linkDraft.url} onChange={event=>setLinkDraft({...linkDraft,url:event.target.value})} placeholder="https://ejemplo.com" className={input}/><div><button className="secondary" onClick={()=>setLinkForm(false)}>Cancelar</button><button onClick={addLink}>Agregar acceso</button></div></div>}<div className="gefi-setting-list">{draft.quickLinks.length?draft.quickLinks.map(link=><article key={link.id}><span className="gefi-setting-list-icon"><Link/></span><div><strong>{link.nombre||new URL(link.url).hostname.replace('www.','')}</strong><small>{link.url}</small></div><a href={link.url} target="_blank" rel="noreferrer" aria-label="Abrir enlace"><ExternalLink/></a><button className="danger" onClick={()=>setDraft({...draft,quickLinks:draft.quickLinks.filter(item=>item.id!==link.id)})} aria-label="Eliminar acceso"><Trash2/></button></article>):<Empty text="Todavía no agregaste accesos directos."/>}</div></div>;
  if(active==='trash')return <div className="gefi-setting-card"><div className="gefi-setting-card-head"><ArchiveRestore/><div><h3>Papelera de movimientos</h3><p>Los movimientos se eliminan definitivamente después de 30 días.</p></div><span className="gefi-setting-count">{trashedTxs.length}</span></div><div className="gefi-setting-list">{trashedTxs.length?trashedTxs.map(transaction=>{const days=Math.max(1,30-Math.floor((Date.now()-(transaction.deletedAt||Date.now()))/86400000));return <article key={transaction.id}><span className="gefi-setting-list-icon"><ArchiveRestore/></span><div><strong>{transaction.motivo||transaction.categoria}</strong><small>{money(transaction.monto,transaction.moneda||draft.monedaBase)} · {days} días restantes</small></div><button className="restore" onClick={()=>onRestoreTx(transaction.id)}>Restaurar</button><button className="danger" onClick={()=>setDeleteTrash(transaction)} aria-label="Eliminar definitivamente"><Trash2/></button></article>}):<Empty text="La papelera está vacía."/>}</div></div>;
  if(active==='accessibility')return <div className="gefi-setting-component"><AccessibilityPanel value={draft.fontScale||'normal'} onChange={fontScale=>setDraft({...draft,fontScale})}/></div>;
  return <div className="gefi-setting-card"><div className="gefi-setting-card-head"><Database/><div><h3>Respaldo de datos</h3><p>Descargá una copia o recuperá información desde un archivo JSON.</p></div></div><div className="gefi-backup-actions"><button onClick={onExport}><Download/>Descargar respaldo</button><label><Database/>Elegir archivo<input type="file" accept="application/json,.json" onChange={event=>setImportFile(event.target.files?.[0]||null)}/></label></div>{importFile&&<div className="gefi-import-file"><span><strong>{importFile.name}</strong><small>El archivo se combinará con tus datos actuales.</small></span><button disabled={saving} onClick={async()=>{setSaving(true);try{await onImport(importFile);setImportFile(null);setNotice('Respaldo importado correctamente.')}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo importar el respaldo.')}finally{setSaving(false)}}}>Importar ahora</button></div>}</div>;
 };
 return <div className="gefi-settings-overlay"><section role="dialog" aria-modal="true" aria-label="Configuración" className="gefi-settings-shell"><header className="gefi-settings-topbar"><div className="gefi-settings-brand"><span><Settings/></span><div><small>GEFI</small><h2>Configuración</h2></div></div><button onClick={onClose} aria-label="Cerrar configuración"><X/></button></header><div className="gefi-settings-workspace"><aside className="gefi-settings-sidebar"><div className="gefi-settings-sidebar-intro"><strong>Tu espacio</strong><p>Personalizá GeFi y administrá tus datos.</p></div>{[...new Set(sections.map(item=>item.group))].map(group=><nav key={group} aria-label={group}><small>{group}</small>{sections.filter(item=>item.group===group).map(item=>{const Icon=item.icon;return <button key={item.id} className={active===item.id?'active':''} onClick={()=>open(item.id)}><span><Icon/></span><div><strong>{item.title}</strong><small>{item.description}</small></div><ChevronRight/></button>})}</nav>)}</aside><main className="gefi-settings-main"><header className="gefi-settings-section-head"><div><button className="gefi-settings-mobile-back" onClick={()=>setActive('preferences')} aria-label="Volver al índice">Configuración</button><h1>{current.title}</h1><p>{current.description}</p></div></header><div className="gefi-settings-section-body">{sectionContent()}{error&&<p className="gefi-settings-feedback error">{error}</p>}{notice&&<p className="gefi-settings-feedback success">{notice}</p>}</div><footer className="gefi-settings-footer"><span>Los cambios de esta sección se guardarán en tu cuenta.</span><div><button className="secondary" onClick={onClose}>Cancelar</button><button disabled={saving} onClick={save}>{saving?'Guardando…':'Guardar cambios'}</button></div></footer></main></div></section>{deleteAccount&&<Confirm title="Eliminar cuenta" text={`¿Querés eliminar ${deleteAccount.nombre}? Los movimientos existentes conservarán sus importes.`} confirm="Sí, eliminar" onCancel={()=>setDeleteAccount(null)} onConfirm={async()=>{await onDeleteAccount(deleteAccount.id);setDeleteAccount(null)}}/>}{deleteTrash&&<Confirm title="Eliminar definitivamente" text={`¿Querés eliminar para siempre ${deleteTrash.motivo||deleteTrash.categoria}? Esta acción no se puede deshacer.`} confirm="Eliminar para siempre" onCancel={()=>setDeleteTrash(null)} onConfirm={async()=>{await onPermanentlyDeleteTx(deleteTrash.id);setDeleteTrash(null)}}/>}</div>;
}

function SettingToggle({title,description,checked,onChange}:{title:string;description:string;checked:boolean;onChange:(checked:boolean)=>void}){return <label className="gefi-setting-toggle"><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i aria-hidden="true"/></label>}
function Empty({text}:{text:string}){return <div className="gefi-settings-empty"><Settings/><p>{text}</p></div>}
function Confirm({title,text,confirm,onCancel,onConfirm}:{title:string;text:string;confirm:string;onCancel:()=>void;onConfirm:()=>void|Promise<void>}){return <div className="gefi-settings-confirm"><section role="alertdialog" aria-modal="true"><h3>{title}</h3><p>{text}</p><div><button onClick={onCancel}>Cancelar</button><button className="danger" onClick={()=>void onConfirm()}>{confirm}</button></div></section></div>}
