import { CalendarCheck2, MailCheck } from 'lucide-react';
import { MonthlyClosure } from '../types';

export default function MonthlyClosurePanel({ closures, currency, language = 'es', hidden = false }: { closures: MonthlyClosure[]; currency: string; language?: 'es'|'en'; hidden?: boolean }) {
  const english = language === 'en';
  const locale = english ? 'en-US' : 'es-AR';
  const money = (value: number, currencyCode = currency) => hidden ? '••••' : new Intl.NumberFormat(locale, { style: 'currency', currency: currencyCode, maximumFractionDigits: 0 }).format(value);
  const latest = closures[0];
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900">
    <div className="flex items-start justify-between gap-3"><div className="flex gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950/40 dark:text-indigo-300"><CalendarCheck2 className="h-4 w-4"/></span><div><h3 className="text-sm font-bold">{english?'Monthly close':'Cierre mensual'}</h3><p className="mt-0.5 text-[11px] text-slate-400">{english?'A fixed snapshot of each completed month.':'Una foto fija de cada mes finalizado.'}</p></div></div>{latest?.emailStatus==='sent'&&<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300"><MailCheck className="h-3 w-3"/>{english?'Email sent':'Correo enviado'}</span>}</div>
    {!latest?<p className="mt-4 rounded-xl bg-slate-50 p-4 text-center text-xs text-slate-500 dark:bg-slate-950 dark:text-slate-400">{english?'Your first close will be generated automatically on the first day of next month.':'Tu primer cierre se generará automáticamente el primer día del próximo mes.'}</p>:<div className="mt-4 space-y-3">{closures.slice(0,6).map(item=><article key={item.id} className="rounded-xl border border-slate-100 p-3 dark:border-slate-800"><div className="flex items-center justify-between gap-3"><strong className="text-xs capitalize">{new Intl.DateTimeFormat(locale,{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${item.period}-01T12:00:00Z`))}</strong><span className="font-mono text-xs font-bold text-blue-600 dark:text-blue-300">{money(item.closingPatrimony,item.currency)}</span></div><div className="mt-2 grid grid-cols-3 gap-2 text-[10px]"><span className="text-emerald-600">{english?'Income':'Ingresos'}<b className="block font-mono">{money(item.income,item.currency)}</b></span><span className="text-rose-600">{english?'Expenses':'Gastos'}<b className="block font-mono">{money(item.expense,item.currency)}</b></span><span className="text-amber-600">{english?'Invested':'Invertido'}<b className="block font-mono">{money(item.invested,item.currency)}</b></span></div></article>)}</div>}
  </section>;
}
