import { useEffect, useMemo, useState } from 'react';
import { Bell, CalendarDays, Check, Plus, Trash2 } from 'lucide-react';
import { PaymentReminder } from '../types';

type Props = { reminders: PaymentReminder[]; currency: string; language?: 'es' | 'en'; hidden?: boolean; onChange: (reminders: PaymentReminder[]) => void };
const localDate = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; };
const daysBetween = (from: string, to: string) => Math.round((new Date(`${to}T12:00:00`).getTime() - new Date(`${from}T12:00:00`).getTime()) / 86400000);

export default function PaymentCalendar({ reminders, currency, language = 'es', hidden = false, onChange }: Props) {
  const [formOpen,setFormOpen]=useState(false), [error,setError]=useState(''), [draft,setDraft]=useState({nombre:'',monto:'',fecha:localDate(),avisoDias:'3'});
  const locale=language==='en'?'en-US':'es-AR', today=localDate();
  const ordered=useMemo(()=>[...reminders].sort((left,right)=>left.fecha.localeCompare(right.fecha)),[reminders]);
  const money=(value:number,code=currency)=>new Intl.NumberFormat(locale,{style:'currency',currency:code,maximumFractionDigits:0}).format(value);
  const status=(item:PaymentReminder)=>{if(item.estado==='Pagado')return {label:'Pagado',tone:'text-emerald-700 bg-emerald-50 dark:text-emerald-300 dark:bg-emerald-950/30'};const days=daysBetween(today,item.fecha);if(days<0)return {label:`Venció hace ${Math.abs(days)} día${Math.abs(days)===1?'':'s'}`,tone:'text-rose-700 bg-rose-50 dark:text-rose-300 dark:bg-rose-950/30'};if(days===0)return {label:'Vence hoy',tone:'text-orange-700 bg-orange-50 dark:text-orange-300 dark:bg-orange-950/30'};if(days<=item.avisoDias)return {label:`Vence en ${days} día${days===1?'':'s'}`,tone:'text-amber-700 bg-amber-50 dark:text-amber-300 dark:bg-amber-950/30'};return {label:new Intl.DateTimeFormat(locale,{day:'numeric',month:'short'}).format(new Date(`${item.fecha}T12:00:00`)),tone:'text-slate-600 bg-slate-100 dark:text-slate-300 dark:bg-slate-800'};};
  useEffect(()=>{if(!('Notification' in window)||Notification.permission!=='granted')return;ordered.filter(item=>item.estado==='Pendiente'&&daysBetween(today,item.fecha)<=item.avisoDias).forEach(item=>{const key=`gefi:payment-alert:${item.id}:${today}`;if(localStorage.getItem(key))return;const info=status(item);new Notification(`GeFi · ${info.label}`,{body:`${item.nombre}${item.monto?` · ${money(item.monto,item.moneda)}`:''}`,icon:'/Gestor-Financiero/favicon.svg'});localStorage.setItem(key,'1')})},[ordered,today]);
  const add=()=>{const amount=Number(draft.monto||0),notice=Number(draft.avisoDias);if(!draft.nombre.trim()||!draft.fecha||!Number.isFinite(notice)||notice<0){setError('Completá el nombre, la fecha y los días de aviso.');return}onChange([...reminders,{id:crypto.randomUUID(),nombre:draft.nombre.trim(),monto:amount>0?amount:undefined,moneda:currency,fecha:draft.fecha,estado:'Pendiente',avisoDias:notice}]);setDraft({nombre:'',monto:'',fecha:localDate(),avisoDias:'3'});setFormOpen(false);setError('')};
  const enableNotifications=async()=>{if(!('Notification' in window)){setError('Este navegador no admite notificaciones.');return}const permission=await Notification.requestPermission();if(permission!=='granted')setError('No se habilitaron las notificaciones del dispositivo.')};
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-5">
    <div className="flex items-start justify-between gap-3"><div className="flex gap-2"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-950/40 dark:text-blue-300"><CalendarDays className="h-4 w-4"/></span><div><h3 className="text-sm font-bold">Calendario de pagos</h3><p className="mt-0.5 text-[11px] text-slate-400">Avisos próximos, del día y vencidos.</p></div></div><button type="button" onClick={()=>setFormOpen(true)} className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 text-white active:scale-95" aria-label="Agregar recordatorio"><Plus className="h-4 w-4"/></button></div>
    {typeof Notification!=='undefined'&&Notification.permission!=='granted'&&<button type="button" onClick={()=>void enableNotifications()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-3 py-2.5 text-xs font-bold text-blue-700 active:scale-[.99] dark:border-blue-900/60 dark:bg-blue-950/30 dark:text-blue-300"><Bell className="h-4 w-4"/>Activar notificaciones</button>}
    {formOpen&&<div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><input autoFocus value={draft.nombre} onChange={event=>setDraft({...draft,nombre:event.target.value})} placeholder="Ej: Internet" className="col-span-2 rounded-lg border border-slate-200 bg-white p-2.5 text-xs dark:border-slate-700 dark:bg-slate-900"/><input type="number" min="0" step="any" value={draft.monto} onChange={event=>setDraft({...draft,monto:event.target.value})} placeholder="Monto opcional" className="rounded-lg border border-slate-200 bg-white p-2.5 text-xs dark:border-slate-700 dark:bg-slate-900"/><input type="date" value={draft.fecha} onChange={event=>setDraft({...draft,fecha:event.target.value})} className="rounded-lg border border-slate-200 bg-white p-2.5 text-xs dark:border-slate-700 dark:bg-slate-900"/><label className="col-span-2 text-[10px] text-slate-500">Avisar con anticipación<input type="number" min="0" value={draft.avisoDias} onChange={event=>setDraft({...draft,avisoDias:event.target.value})} className="mt-1 w-full rounded-lg border border-slate-200 bg-white p-2.5 text-xs dark:border-slate-700 dark:bg-slate-900"/></label><div className="col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setFormOpen(false)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs dark:border-slate-700">Cancelar</button><button type="button" onClick={add} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Guardar recordatorio</button></div></div>}
    {error&&<p className="mt-3 rounded-lg bg-rose-50 p-2.5 text-xs text-rose-600 dark:bg-rose-950/30 dark:text-rose-300">{error}</p>}
    <div className="mt-4 divide-y divide-slate-100 dark:divide-slate-800">{ordered.length?ordered.map(item=>{const info=status(item);return <div key={item.id} className="flex items-center gap-3 py-3"><button type="button" onClick={()=>onChange(reminders.map(entry=>entry.id===item.id?{...entry,estado:entry.estado==='Pagado'?'Pendiente':'Pagado'}:entry))} className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg border ${item.estado==='Pagado'?'border-emerald-500 bg-emerald-500 text-white':'border-slate-200 text-slate-400 dark:border-slate-700'}`} aria-label={item.estado==='Pagado'?'Marcar pendiente':'Marcar pagado'}>{item.estado==='Pagado'&&<Check className="h-4 w-4"/>}</button><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className={`truncate text-xs ${item.estado==='Pagado'?'line-through opacity-60':''}`}>{item.nombre}</strong><span className={`shrink-0 rounded-full px-2 py-0.5 text-[9px] font-bold ${info.tone}`}>{info.label}</span></div><p className="mt-1 text-[10px] text-slate-400">{item.fecha}{item.monto?` · ${hidden?'••••':money(item.monto,item.moneda)}`:''}</p></div><button type="button" onClick={()=>onChange(reminders.filter(entry=>entry.id!==item.id))} className="p-2 text-slate-400 hover:text-rose-600" aria-label="Eliminar recordatorio"><Trash2 className="h-4 w-4"/></button></div>}):<p className="py-5 text-center text-xs text-slate-400">Todavía no agregaste pagos al calendario.</p>}</div>
  </section>;
}
