import { useState } from 'react';
import { Plus, Trash2, Target } from 'lucide-react';
import { SavingsGoal } from '../types';

type Props = { goals: SavingsGoal[]; saved: number; hidden?: boolean; onChange: (goals: SavingsGoal[]) => void };
const money = (value: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value);

export default function SavingsGoalsPanel({ goals, saved, hidden = false, onChange }: Props) {
  const [open, setOpen] = useState(false), [name, setName] = useState(''), [amount, setAmount] = useState('');
  const add = () => { const objetivo = Number(amount); if (!name.trim() || !Number.isFinite(objetivo) || objetivo <= 0) return; onChange([...goals, { id: crypto.randomUUID(), nombre: name.trim(), objetivo }]); setName(''); setAmount(''); setOpen(false); };
  return <section className="rounded-2xl border border-violet-200 bg-white p-4 shadow-sm dark:border-violet-900/60 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><Target className="mt-0.5 h-4 w-4 text-violet-600"/><div><h3 className="text-sm font-bold">Metas de ahorro</h3><p className="mt-1 text-[11px] text-slate-400">Tus movimientos de ahorro actualizan el progreso.</p></div></div><button type="button" onClick={() => setOpen(value => !value)} className="inline-flex items-center gap-1 rounded-lg bg-violet-600 px-2.5 py-1.5 text-[10px] font-bold text-white"><Plus className="h-3.5 w-3.5"/>Agregar</button></div>{open&&<div className="mt-3 grid gap-2 rounded-xl bg-violet-50 p-3 dark:bg-violet-950/25 sm:grid-cols-[1fr_120px_auto]"><input autoFocus value={name} onChange={event => setName(event.target.value)} placeholder="Ej: Fondo de emergencia" className="rounded-lg border border-violet-200 bg-white px-2.5 py-2 text-xs dark:border-violet-900 dark:bg-slate-950"/><input type="number" min="0.01" step="any" value={amount} onChange={event => setAmount(event.target.value)} placeholder="Objetivo" className="rounded-lg border border-violet-200 bg-white px-2.5 py-2 text-xs dark:border-violet-900 dark:bg-slate-950"/><button type="button" onClick={add} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold text-white">Guardar</button></div>}<div className="mt-3 space-y-3">{goals.map(goal => { const percent = Math.min(100, saved / goal.objetivo * 100); return <div key={goal.id}><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="font-medium">{goal.nombre}</span><span className="flex items-center gap-2"><span className="text-slate-500 dark:text-slate-400">{hidden ? '••••' : `${money(saved)} / ${money(goal.objetivo)}`}</span><button type="button" onClick={() => onChange(goals.filter(item => item.id !== goal.id))} title="Eliminar meta" className="text-slate-400 hover:text-rose-600"><Trash2 className="h-3.5 w-3.5"/></button></span></div><div className="h-2 overflow-hidden rounded-full bg-violet-100 dark:bg-violet-950"><div className="h-full rounded-full bg-violet-600" style={{width:`${percent}%`}}/></div></div>})}{goals.length===0&&<p className="rounded-xl bg-violet-50 p-3 text-xs text-violet-700 dark:bg-violet-950/25 dark:text-violet-300">Creá una meta para visualizar el avance de tus ahorros.</p>}</div></section>;
}
