import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, Mail, Send, X } from 'lucide-react';

const ENDPOINT='https://gefi-support.denislautaro6.workers.dev/';
type Props={open:boolean;onClose:()=>void;initialName?:string|null;initialEmail?:string|null;language?:'es'|'en';source:string};

export default function SupportModal({open,onClose,initialName,initialEmail,language='es',source}:Props){
 const en=language==='en',[name,setName]=useState(initialName||''),[email,setEmail]=useState(initialEmail||''),[message,setMessage]=useState(''),[website,setWebsite]=useState(''),[sending,setSending]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setName(initialName||'');setEmail(initialEmail||'');setMessage('');setWebsite('');setSent(false);setError('')}},[open,initialName,initialEmail]);
 useEffect(()=>{if(!open)return;const key=(event:KeyboardEvent)=>event.key==='Escape'&&onClose();window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open,onClose]);
 if(!open)return null;
 const submit=async(event:FormEvent)=>{event.preventDefault();setSending(true);setError('');try{const response=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,message,website,source})});if(!response.ok)throw new Error();setSent(true)}catch{setError(en?'We could not send your message. Please try again.':'No pudimos enviar el mensaje. Intentá nuevamente.')}finally{setSending(false)}};
 return <div className="gefi-support-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="gefi-support-dialog" role="dialog" aria-modal="true" aria-label={en?'Contact support':'Contactar soporte'}>{sent?<div className="gefi-support-success"><CheckCircle2/><h3>{en?'Message sent':'Mensaje enviado'}</h3><p>{en?'Support will reply directly to your email.':'Soporte te responderá directamente a tu correo.'}</p><button onClick={onClose}>{en?'Close':'Cerrar'}</button></div>:<><header><span><Mail/></span><div><small>GEFI SUPPORT</small><h2>{en?'Contact support':'Contactar soporte'}</h2></div><button onClick={onClose} aria-label={en?'Close':'Cerrar'}><X/></button></header><form onSubmit={submit}><p>{en?'Tell us what happened and we will reply to your account email.':'Contanos qué pasó y responderemos al correo de tu cuenta.'}</p><div className="gefi-support-fields"><label>{en?'Name':'Nombre'}<input required minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><label>{en?'Email':'Correo'}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div><label>{en?'Message':'Mensaje'}<textarea required minLength={10} rows={6} value={message} onChange={e=>setMessage(e.target.value)} placeholder={en?'How can we help you?':'¿Cómo podemos ayudarte?'}/></label><label className="gefi-support-honeypot">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label>{error&&<p className="gefi-support-error" role="alert">{error}</p>}<button className="gefi-support-submit" disabled={sending}><Send/>{sending?(en?'Sending…':'Enviando…'):(en?'Send message':'Enviar mensaje')}</button><small className="gefi-support-note">gefisupport@gmail.com</small></form></>}</section></div>
}
