import React, { useEffect, useState } from 'react';
import { Trash2, Pencil, Search, ChevronDown, ChevronUp, X, AlertTriangle } from 'lucide-react';
import { Account, Transaction } from '../types';

export default function TransactionList({ transactions, onDeleteTransaction, onEditTransaction, loading, hideBalances = false, accounts = [] }: { transactions: Transaction[]; onDeleteTransaction: (id: string) => Promise<void>; onEditTransaction: (t: Transaction) => Promise<void>; loading: boolean; hideBalances?: boolean; accounts?: Account[] }) {
  const [search, setSearch] = useState(''); const [type, setType] = useState(''); const [currency, setCurrency] = useState(''); const [account, setAccount] = useState(''); const [expanded,setExpanded]=useState(false);
  const [editDraft,setEditDraft]=useState<Transaction|null>(null), [deleteTarget,setDeleteTarget]=useState<Transaction|null>(null), [saving,setSaving]=useState(false), [modalError,setModalError]=useState('');
  useEffect(() => {
    const syncEditedDate = (event: Event) => {
      const input = event.target as HTMLInputElement;
      if (input.type !== 'date' || !input.closest('[role="dialog"]')) return;
      setEditDraft(current => current ? {...current, fecha: input.value} : current);
    };
    document.addEventListener('input', syncEditedDate, true);
    return () => document.removeEventListener('input', syncEditedDate, true);
  }, []);
  const format = (n: number, c = 'ARS') => new Intl.NumberFormat('es-AR', { style: 'currency', currency: c, maximumFractionDigits: 2 }).format(n);
  const list = transactions.filter(t => (!search || `${t.motivo} ${t.categoriaDetalle || ''}`.toLowerCase().includes(search.toLowerCase())) && (!type || t.categoria === type) && (!currency || (t.moneda || 'ARS') === currency) && (!account || t.cuentaOrigen === account || t.cuentaDestino === account)).sort((a,b) => b.fecha.localeCompare(a.fecha) || b.createdAt-a.createdAt);
  const visibleList=expanded?list:list.slice(0,10);
  const saveEdit=async()=>{if(!editDraft)return;if(!editDraft.motivo.trim()||!editDraft.fecha||Number(editDraft.monto)<=0){setModalError('Completá la fecha, el motivo y un importe mayor que cero.');return}setSaving(true);setModalError('');try{await onEditTransaction({...editDraft,motivo:editDraft.motivo.trim(),monto:Number(editDraft.monto)});setEditDraft(null)}catch{setModalError('No se pudo guardar el cambio. Intentá nuevamente.')}finally{setSaving(false)}};
  const confirmDelete=async()=>{if(!deleteTarget)return;setSaving(true);try{await onDeleteTransaction(deleteTarget.id);setDeleteTarget(null)}catch{setModalError('No se pudo eliminar el movimiento. Intentá nuevamente.')}finally{setSaving(false)}};
  return <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm">
    <div className="flex flex-wrap gap-2 items-center justify-between mb-4"><h3 className="text-sm font-bold">Historial de movimientos <span className="text-slate-400 text-xs">({list.length})</span></h3><div className="flex flex-wrap gap-2"><div className="relative"><Search className="w-3.5 h-3.5 absolute left-2 top-2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar" className="pl-7 p-1.5 text-xs rounded border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950"/></div><select value={type} onChange={e=>setType(e.target.value)} className="p-1.5 text-xs rounded border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950"><option value="">Todos los tipos</option>{['Ingreso','Gasto','Inversion','Efectivo','Gasto efectivo','Transferencia','Prestamo','Ef+','Ef-'].map(x=><option key={x}>{x}</option>)}</select><select value={currency} onChange={e=>setCurrency(e.target.value)} className="p-1.5 text-xs rounded border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950"><option value="">Monedas</option>{[...new Set(transactions.map(t=>t.moneda || 'ARS'))].map(x=><option key={x}>{x}</option>)}</select><select value={account} onChange={e=>setAccount(e.target.value)} className="p-1.5 text-xs rounded border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950"><option value="">Cuentas</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></div></div>
    {loading ? <p className="text-sm text-slate-400 py-8 text-center">Cargando movimientos…</p> : <div><div className="overflow-auto"><table className="w-full text-xs"><thead className="text-left text-slate-400 border-b dark:border-slate-800"><tr><th className="p-2">Fecha</th><th className="p-2">Tipo</th><th className="p-2">Detalle</th><th className="p-2">Cuenta</th><th className="p-2 text-right">Importe</th><th/></tr></thead><tbody>{visibleList.map(t=>{const color=t.categoria==='Ingreso'||t.categoria==='Ef+'?'text-emerald-600':t.categoria==='Inversion'?'text-amber-600':t.categoria==='Ahorro'?'text-violet-600 dark:text-violet-400':t.categoria==='Transferencia'?'text-blue-600':'text-rose-600'; const acct=accounts.find(a=>a.id===t.cuentaOrigen)?.nombre || accounts.find(a=>a.id===t.cuentaDestino)?.nombre || '—'; return <tr key={t.id} className="border-b dark:border-slate-800/70"><td className="p-2">{t.fecha}</td><td className="p-2"><span className={color}>{t.categoria}</span></td><td className="p-2">{t.motivo}<small className="block text-slate-400">{t.categoriaDetalle}</small></td><td className="p-2">{acct}</td><td className={`p-2 text-right font-mono font-bold ${color}`}>{hideBalances?'••••':format(t.monto,t.moneda||'ARS')}</td><td className="p-2 whitespace-nowrap"><button title="Editar" onClick={()=>{setModalError('');setEditDraft({...t})}} className="p-1 text-slate-400 hover:text-blue-600"><Pencil className="w-3.5 h-3.5"/></button><button title="Eliminar" onClick={()=>{setModalError('');setDeleteTarget(t)}} className="p-1 text-slate-400 hover:text-rose-600"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>})}</tbody></table>{!list.length&&<p className="py-8 text-center text-slate-400">No hay movimientos con esos filtros.</p>}</div>{list.length>10&&<button onClick={()=>setExpanded(x=>!x)} className="mx-auto mt-4 flex items-center gap-1.5 text-xs font-bold text-blue-600 dark:text-blue-400">{expanded?<><ChevronUp className="w-4 h-4"/>Ver menos</>:<><ChevronDown className="w-4 h-4"/>Ver más ({list.length-10})</>}</button>}</div>}
    {editDraft&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/60 backdrop-blur-sm p-4" onMouseDown={e=>e.target===e.currentTarget&&setEditDraft(null)}><div role="dialog" aria-modal="true" aria-labelledby="edit-title" className="w-full max-w-md rounded-2xl bg-white dark:bg-slate-900 p-6 shadow-2xl border border-slate-200 dark:border-slate-700"><div className="flex items-center justify-between"><div><h3 id="edit-title" className="font-bold text-base">Modificar movimiento</h3><p className="text-xs text-slate-400 mt-1">Editá los datos y presioná Guardar cambios.</p></div><button onClick={()=>setEditDraft(null)} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"><X className="w-4 h-4"/></button></div><div className="grid grid-cols-2 gap-3 mt-5"><label className="text-xs text-slate-500 dark:text-slate-400">Fecha<input type="date" value={editDraft.fecha} onChange={e=>setEditDraft({...editDraft,fecha:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 p-2.5 text-slate-900 dark:text-slate-100"/></label><label className="text-xs text-slate-500 dark:text-slate-400">Importe<input type="number" min="0.01" step="any" value={editDraft.monto} onChange={e=>setEditDraft({...editDraft,monto:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 p-2.5 text-slate-900 dark:text-slate-100"/></label><label className="col-span-2 text-xs text-slate-500 dark:text-slate-400">Motivo / descripción<input autoFocus value={editDraft.motivo} onChange={e=>setEditDraft({...editDraft,motivo:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 p-2.5 text-slate-900 dark:text-slate-100"/></label><label className="col-span-2 text-xs text-slate-500 dark:text-slate-400">Categoría / detalle<input value={editDraft.categoriaDetalle||''} onChange={e=>setEditDraft({...editDraft,categoriaDetalle:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 p-2.5 text-slate-900 dark:text-slate-100"/></label></div>{modalError&&<p className="mt-3 rounded-lg bg-rose-50 dark:bg-rose-950/30 p-2.5 text-xs text-rose-600 dark:text-rose-300">{modalError}</p>}<div className="flex justify-end gap-2 mt-5"><button onClick={()=>setEditDraft(null)} className="rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2 text-xs font-bold">Cancelar</button><button disabled={saving} onClick={saveEdit} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-60">{saving?'Guardando…':'Guardar cambios'}</button></div></div></div>}
    {deleteTarget&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/60 backdrop-blur-sm p-4" onMouseDown={e=>e.target===e.currentTarget&&setDeleteTarget(null)}><div role="alertdialog" aria-modal="true" aria-labelledby="delete-title" className="w-full max-w-sm rounded-2xl bg-white dark:bg-slate-900 p-6 shadow-2xl border border-slate-200 dark:border-slate-700"><div className="flex gap-3"><div className="grid place-items-center w-10 h-10 shrink-0 rounded-full bg-rose-100 dark:bg-rose-950/40"><AlertTriangle className="w-5 h-5 text-rose-600"/></div><div><h3 id="delete-title" className="font-bold text-base">Enviar a la papelera</h3><p className="text-sm text-slate-500 dark:text-slate-400 mt-1">¿Querés enviar <strong className="text-slate-800 dark:text-slate-100">{deleteTarget.motivo}</strong> a la papelera? Podrás restaurarlo durante 30 días desde Configuración.</p></div></div>{modalError&&<p className="mt-3 rounded-lg bg-rose-50 dark:bg-rose-950/30 p-2.5 text-xs text-rose-600 dark:text-rose-300">{modalError}</p>}<div className="flex justify-end gap-2 mt-5"><button onClick={()=>setDeleteTarget(null)} className="rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2 text-xs font-bold">Cancelar</button><button disabled={saving} onClick={confirmDelete} className="rounded-lg bg-rose-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-60">{saving?'Moviendo…':'Enviar a papelera'}</button></div></div></div>}
  </section>;
}
