import React, { useEffect, useState } from 'react';
import { AlertTriangle, ChevronDown, ChevronUp, Pencil, Search, Trash2, X } from 'lucide-react';
import { Account, Transaction } from '../types';
import { useToast } from '../hooks/useToast';

type Props = { transactions: Transaction[]; onDeleteTransaction: (id: string) => Promise<void>; onEditTransaction: (transaction: Transaction) => Promise<void>; loading: boolean; hideBalances?: boolean; accounts?: Account[] };

export default function TransactionList({ transactions, onDeleteTransaction, onEditTransaction, loading, hideBalances = false, accounts = [] }: Props) {
  const toast = useToast();
  const [search, setSearch] = useState(''), [type, setType] = useState(''), [currency, setCurrency] = useState(''), [account, setAccount] = useState(''), [expanded, setExpanded] = useState(false);
  const [editDraft, setEditDraft] = useState<Transaction | null>(null), [deleteTarget, setDeleteTarget] = useState<Transaction | null>(null), [saving, setSaving] = useState(false), [modalError, setModalError] = useState(''), [isMobile, setIsMobile] = useState(() => window.matchMedia('(max-width: 639px)').matches);
  const [selectedIds,setSelectedIds]=useState<Set<string>>(new Set()),[bulkDeleteOpen,setBulkDeleteOpen]=useState(false);
  useEffect(() => { const media = window.matchMedia('(max-width: 639px)'); const syncViewport = () => setIsMobile(media.matches); syncViewport(); media.addEventListener('change', syncViewport); return () => media.removeEventListener('change', syncViewport); }, []);
  useEffect(() => { const syncDate = (event: Event) => { const input = event.target as HTMLInputElement; if (input.type === 'date' && input.closest('[role="dialog"]')) setEditDraft(current => current ? { ...current, fecha: input.value } : current); }; document.addEventListener('input', syncDate, true); return () => document.removeEventListener('input', syncDate, true); }, []);
  const format = (value: number, code = 'ARS') => new Intl.NumberFormat('es-AR', { style: 'currency', currency: code, maximumFractionDigits: 2 }).format(value);
  const isCorrection = (t: Transaction) => t.categoriaDetalle === 'Corrección de saldo' || /^Corrección de\s/i.test(t.motivo || '');
  const typeFor = (t: Transaction) => isCorrection(t) ? 'Corrección' : t.categoria;
  const colorFor = (t: Transaction) => isCorrection(t) ? 'text-blue-600 dark:text-blue-400' : t.categoria === 'Ingreso' || t.categoria === 'Ef+' ? 'text-emerald-600' : t.categoria === 'Inversion' ? 'text-amber-600' : t.categoria === 'Ahorro' ? 'text-violet-600 dark:text-violet-400' : t.categoria === 'Transferencia' ? 'text-blue-600' : 'text-rose-600';
  const accountFor = (t: Transaction) => accounts.find(a => a.id === t.cuentaOrigen)?.nombre || accounts.find(a => a.id === t.cuentaDestino)?.nombre || 'Sin cuenta';
  const list = transactions.filter(t => (!search || `${t.motivo} ${t.categoriaDetalle || ''}`.toLowerCase().includes(search.toLowerCase())) && (!type || t.categoria === type) && (!currency || (t.moneda || 'ARS') === currency) && (!account || t.cuentaOrigen === account || t.cuentaDestino === account)).sort((a, b) => b.fecha.localeCompare(a.fecha) || b.createdAt - a.createdAt);
  const initialLimit = isMobile ? 4 : 10;
  const visibleList = expanded ? list : list.slice(0, initialLimit);
  const saveEdit = async () => { if (!editDraft) return; if (!editDraft.fecha || Number(editDraft.monto) <= 0) { setModalError('Completá la fecha y un importe mayor que cero.'); return; } setSaving(true); setModalError(''); try { await onEditTransaction({ ...editDraft, motivo: (editDraft.motivo || '').trim(), monto: Number(editDraft.monto) }); setEditDraft(null); } catch { setModalError('No se pudo guardar el cambio. Intentá nuevamente.'); } finally { setSaving(false); } };
  const confirmDelete = async () => { if (!deleteTarget) return; const target=deleteTarget;setDeleteTarget(null);setSaving(true); try { await onDeleteTransaction(target.id);toast.success('Movimiento eliminado'); } catch { toast.error('No se pudo eliminar el movimiento. Intentá nuevamente.'); } finally { setSaving(false); } };
  const toggleSelected=(id:string)=>setSelectedIds(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});
  const confirmBulkDelete=async()=>{const ids=[...selectedIds];setBulkDeleteOpen(false);setSaving(true);try{await Promise.all(ids.map(onDeleteTransaction));setSelectedIds(new Set());toast.success(`${ids.length} movimientos eliminados`)}catch{toast.error('No se pudieron eliminar todos los movimientos. Intentá nuevamente.')}finally{setSaving(false)}};
  const actions = (t: Transaction) => <div className="flex shrink-0 gap-1"><label title="Seleccionar" className={`grid h-9 w-9 cursor-pointer place-items-center rounded-lg border ${selectedIds.has(t.id)?'border-blue-500 bg-blue-50 dark:bg-blue-950/40':'border-slate-200 dark:border-slate-700'}`}><input type="checkbox" checked={selectedIds.has(t.id)} onChange={()=>toggleSelected(t.id)} aria-label={`Seleccionar ${t.motivo}`} className="h-4 w-4 accent-blue-600"/></label><button aria-label={`Editar ${t.motivo}`} title="Editar" onClick={() => { setModalError(''); setEditDraft({ ...t }); }} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 text-slate-500 hover:text-blue-600 dark:border-slate-700"><Pencil className="h-4 w-4" /></button><button aria-label={`Eliminar ${t.motivo}`} title="Eliminar" onClick={() => { setModalError(''); setDeleteTarget(t); }} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 text-slate-500 hover:text-rose-600 dark:border-slate-700"><Trash2 className="h-4 w-4" /></button></div>;

  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-5">
    <div className="mb-4 space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-bold">Historial de movimientos <span className="text-xs text-slate-400">({list.length})</span></h3><div className="flex gap-2"><button onClick={()=>setSelectedIds(selectedIds.size===visibleList.length?new Set():new Set(visibleList.map(t=>t.id)))} className="min-h-9 rounded-lg border border-slate-200 px-3 text-xs font-bold dark:border-slate-700">{selectedIds.size===visibleList.length&&visibleList.length?'Quitar selección':'Seleccionar visibles'}</button>{selectedIds.size>0&&<button onClick={()=>setBulkDeleteOpen(true)} className="min-h-9 rounded-lg bg-rose-600 px-3 text-xs font-bold text-white">Eliminar ({selectedIds.size})</button>}</div></div><div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap"><div className="relative col-span-2 sm:col-span-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-slate-400"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar movimientos" className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pl-8 pr-2 text-xs dark:border-slate-800 dark:bg-slate-950 sm:w-48"/></div><select value={type} onChange={e => setType(e.target.value)} className="min-w-0 rounded-lg border border-slate-200 bg-slate-50 p-2 text-xs dark:border-slate-800 dark:bg-slate-950"><option value="">Todos los tipos</option>{['Ingreso','Gasto','Inversion','Ahorro','Efectivo','Gasto efectivo','Transferencia','Prestamo','Ef+','Ef-'].map(x => <option key={x}>{x}</option>)}</select><select value={currency} onChange={e => setCurrency(e.target.value)} className="min-w-0 rounded-lg border border-slate-200 bg-slate-50 p-2 text-xs dark:border-slate-800 dark:bg-slate-950"><option value="">Monedas</option>{[...new Set(transactions.map(t => t.moneda || 'ARS'))].map(x => <option key={x}>{x}</option>)}</select><select value={account} onChange={e => setAccount(e.target.value)} className="col-span-2 min-w-0 rounded-lg border border-slate-200 bg-slate-50 p-2 text-xs dark:border-slate-800 dark:bg-slate-950 sm:col-span-1"><option value="">Todas las cuentas</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.nombre}</option>)}</select></div></div>
    {loading ? <p className="py-8 text-center text-sm text-slate-400">Cargando movimientos…</p> : <><div className="space-y-2 sm:hidden">{visibleList.map(t => { const color = colorFor(t); return <article key={t.id} className="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-2"><span className={`text-xs font-bold ${color}`}>{typeFor(t)}</span><span className="text-[10px] text-slate-400">{t.fecha}</span></div><p className="mt-1 break-words text-sm font-medium">{t.motivo}</p><p className="mt-0.5 text-[11px] text-slate-400">{t.categoriaDetalle || 'General'} · {accountFor(t)}</p></div><strong className={`shrink-0 font-mono text-sm ${color}`}>{hideBalances ? '••••' : format(t.monto, t.moneda || 'ARS')}</strong></div><div className="mt-3 flex justify-end">{actions(t)}</div></article>; })}</div><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[680px] text-xs"><thead className="border-b text-left text-slate-400 dark:border-slate-800"><tr><th className="p-2">Fecha</th><th className="p-2">Tipo</th><th className="p-2">Detalle</th><th className="p-2">Cuenta</th><th className="p-2 text-right">Importe</th><th/></tr></thead><tbody>{visibleList.map(t => { const color = colorFor(t); return <tr key={t.id} className="border-b dark:border-slate-800/70"><td className="p-2">{t.fecha}</td><td className="p-2"><span className={color}>{typeFor(t)}</span></td><td className="p-2">{t.motivo}<small className="block text-slate-400">{t.categoriaDetalle}</small></td><td className="p-2">{accountFor(t)}</td><td className={`p-2 text-right font-mono font-bold ${color}`}>{hideBalances ? '••••' : format(t.monto, t.moneda || 'ARS')}</td><td className="p-2">{actions(t)}</td></tr>; })}</tbody></table></div>{!list.length && <p className="py-8 text-center text-slate-400">No hay movimientos con esos filtros.</p>}{list.length > initialLimit && <button onClick={() => setExpanded(x => !x)} className="mx-auto mt-4 flex min-h-10 items-center gap-1.5 px-4 text-xs font-bold text-blue-600 dark:text-blue-400">{expanded ? <><ChevronUp className="h-4 w-4"/>Ver menos</> : <><ChevronDown className="h-4 w-4"/>Ver más ({list.length - initialLimit})</>}</button>}</>}
    {editDraft && <div className="fixed inset-0 z-[80] grid place-items-end overflow-y-auto bg-slate-950/60 p-0 backdrop-blur-sm sm:place-items-center sm:p-4" onMouseDown={e => e.target === e.currentTarget && setEditDraft(null)}><div role="dialog" aria-modal="true" className="max-h-[92dvh] w-full overflow-y-auto rounded-t-2xl border border-slate-200 bg-white p-5 shadow-2xl dark:border-slate-700 dark:bg-slate-900 sm:max-w-md sm:rounded-2xl sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-bold">Modificar movimiento</h3><p className="mt-1 text-xs text-slate-400">Editá los datos y presioná Guardar cambios.</p></div><button aria-label="Cerrar" onClick={() => setEditDraft(null)} className="p-2"><X className="h-4 w-4"/></button></div><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Fecha<input type="date" value={editDraft.fecha} onChange={e => setEditDraft({ ...editDraft, fecha: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-xs text-slate-500">Importe<input type="number" min="0.01" step="any" value={editDraft.monto} onChange={e => setEditDraft({ ...editDraft, monto: Number(e.target.value) })} className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-xs text-slate-500 sm:col-span-2">Motivo / descripción<input value={editDraft.motivo} onChange={e => setEditDraft({ ...editDraft, motivo: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-xs text-slate-500 sm:col-span-2">Categoría / detalle<input value={editDraft.categoriaDetalle || ''} onChange={e => setEditDraft({ ...editDraft, categoriaDetalle: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950"/></label></div>{modalError && <p className="mt-3 rounded-lg bg-rose-50 p-2.5 text-xs text-rose-600 dark:bg-rose-950/30">{modalError}</p>}<div className="mt-5 grid grid-cols-2 gap-2"><button onClick={() => setEditDraft(null)} className="min-h-11 rounded-lg border border-slate-200 text-xs font-bold dark:border-slate-700">Cancelar</button><button disabled={saving} onClick={saveEdit} className="min-h-11 rounded-lg bg-blue-600 text-xs font-bold text-white">{saving ? 'Guardando…' : 'Guardar cambios'}</button></div></div></div>}
    {bulkDeleteOpen&&<div className="fixed inset-0 z-[80] grid place-items-end bg-slate-950/60 p-0 sm:place-items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&setBulkDeleteOpen(false)}><div role="alertdialog" aria-modal="true" className="w-full rounded-t-2xl border border-slate-200 bg-white p-5 shadow-2xl dark:border-slate-700 dark:bg-slate-900 sm:max-w-sm sm:rounded-2xl sm:p-6"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-rose-100"><AlertTriangle className="h-5 w-5 text-rose-600"/></div><div><h3 className="font-bold">Eliminar movimientos seleccionados</h3><p className="mt-1 text-sm text-slate-500">¿Querés enviar {selectedIds.size} movimientos a la papelera?</p></div></div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>setBulkDeleteOpen(false)} className="min-h-11 rounded-lg border border-slate-200 text-xs font-bold dark:border-slate-700">Cancelar</button><button disabled={saving} onClick={confirmBulkDelete} className="min-h-11 rounded-lg bg-rose-600 text-xs font-bold text-white">Eliminar</button></div></div></div>}
    {deleteTarget && <div className="fixed inset-0 z-[80] grid place-items-end bg-slate-950/60 p-0 sm:place-items-center sm:p-4" onMouseDown={e => e.target === e.currentTarget && setDeleteTarget(null)}><div role="alertdialog" aria-modal="true" className="w-full rounded-t-2xl border border-slate-200 bg-white p-5 shadow-2xl dark:border-slate-700 dark:bg-slate-900 sm:max-w-sm sm:rounded-2xl sm:p-6"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-rose-100"><AlertTriangle className="h-5 w-5 text-rose-600"/></div><div><h3 className="font-bold">Enviar a la papelera</h3><p className="mt-1 text-sm text-slate-500">¿Querés enviar <strong>{deleteTarget.motivo}</strong> a la papelera?</p></div></div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={() => setDeleteTarget(null)} className="min-h-11 rounded-lg border border-slate-200 text-xs font-bold dark:border-slate-700">Cancelar</button><button disabled={saving} onClick={confirmDelete} className="min-h-11 rounded-lg bg-rose-600 text-xs font-bold text-white">{saving ? 'Moviendo…' : 'Enviar'}</button></div></div></div>}
  </section>;
}
