import React, { useEffect, useMemo, useRef, useState } from 'react';
import { User, deleteUser, onAuthStateChanged, sendPasswordResetEmail, signOut } from 'firebase/auth';
import { addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, orderBy, query, setDoc, updateDoc } from 'firebase/firestore';
import { Download, Plus, ExternalLink, Link as LinkIcon, Trash2, X, Pencil } from 'lucide-react';
import { auth, db } from './firebase';
import { Account, Loan, FixedExpense, Transaction, UserSettings } from './types';
import Login from './components/Login'; import Header, { MESES } from './components/Header'; import TransactionForm from './components/TransactionForm'; import TransactionList from './components/TransactionList';
import SmartTransactionInput from './components/SmartTransactionInput';
import BudgetPanel from './components/BudgetPanel';
import SavingsGoalsPanel from './components/SavingsGoalsPanel';
import MonthlyReportPanel from './components/MonthlyReportPanel';
import HelpPanel from './components/HelpPanel';
import SecurityPanel from './components/SecurityPanel';
import AccessibilityPanel from './components/AccessibilityPanel';
import MobileNavigation from './components/MobileNavigation';
import PaymentCalendar from './components/PaymentCalendar';
import InvestmentPreferences from './components/InvestmentPreferences';
import { applyLanguage } from './i18n';
import { SUPPORTED_CURRENCIES } from './currencies';

const defaults: UserSettings = { darkMode: false, hideBalances: false, monedaBase: 'ARS', monedas: [...SUPPORTED_CURRENCIES], categorias: ['General','Alimentos','Transporte','Salud','Educación','Hogar','Ocio','Trabajo'], widgets: ['patrimonio','cuentas','efectivo','inversiones'], quickLinks: [], showSavings: true, language: 'es', budgets: {}, savingsGoals: [], fontScale: 'normal', currencySetupCompleted: true, investmentPlatforms: ['IOL','Binance'], paymentReminders: [], monthlyEmailSummary: true, paymentEmailReminders: true };
const regionalCurrency: Record<string,string> = { AR:'ARS', US:'USD', CA:'CAD', MX:'MXN', BR:'BRL', CL:'CLP', CO:'COP', PE:'PEN', UY:'UYU', PY:'PYG', BO:'BOB', EC:'USD', VE:'VES', GB:'GBP', IE:'EUR', ES:'EUR', FR:'EUR', DE:'EUR', IT:'EUR', PT:'EUR', NL:'EUR', BE:'EUR', AT:'EUR', FI:'EUR', GR:'EUR', JP:'JPY', KR:'KRW', CN:'CNY', IN:'INR', AU:'AUD', NZ:'NZD', ZA:'ZAR', CH:'CHF', SE:'SEK', NO:'NOK', DK:'DKK', PL:'PLN', TR:'TRY', AE:'AED', SA:'SAR' };
const localizedDefaults=():UserSettings=>{const locale=typeof navigator==='undefined'?'es-AR':(Intl.DateTimeFormat().resolvedOptions().locale||navigator.language||'es-AR');const country=locale.split('-').pop()?.toUpperCase()||'AR';const currency=regionalCurrency[country]||'USD';const language=locale.toLowerCase().startsWith('en')?'en':'es';return {...defaults,monedaBase:currency,monedas:[currency,...defaults.monedas.filter(code=>code!==currency)],language,currencySetupCompleted:false};};
const today = () => new Date().toISOString().slice(0,10);
const toArs = (t: Transaction) => t.monto * (t.moneda === 'ARS' || !t.moneda ? 1 : Number(t.cotizacion || 1));
const isBalanceCorrection = (t: Pick<Transaction,'motivo'|'categoriaDetalle'>) => t.categoriaDetalle === 'Corrección de saldo' || /^Corrección de\s/i.test(t.motivo || '');
const accountImpact = (t: Pick<Transaction,'categoria'|'monto'|'moneda'|'cotizacion'|'cuentaOrigen'|'cuentaDestino'>, accounts:Account[] = []) => { const value=toArs(t as Transaction); if(t.categoria==='Transferencia'){const origin=accounts.find(a=>a.id===t.cuentaOrigen),destination=accounts.find(a=>a.id===t.cuentaDestino);return (origin&&origin.tipo!=='Efectivo'?-value:0)+(destination&&destination.tipo!=='Efectivo'?value:0)}if(t.categoria==='Ingreso')return value;if(t.categoria==='Gasto'||t.categoria==='Inversion'||t.categoria==='Ahorro'||t.categoria==='Prestamo')return -value;if(t.categoria==='Desinversion')return value;return 0 };
const cashImpact = (t: Pick<Transaction,'categoria'|'monto'|'moneda'|'cotizacion'|'cuentaOrigen'|'cuentaDestino'>, accounts:Account[]) => { const value=toArs(t as Transaction); if(t.categoria==='Ef+')return value;if(t.categoria==='Ef-')return -value;if(t.categoria!=='Transferencia')return 0;const origin=accounts.find(a=>a.id===t.cuentaOrigen),destination=accounts.find(a=>a.id===t.cuentaDestino);return (origin?.tipo==='Efectivo'?-value:0)+(destination?.tipo==='Efectivo'?value:0) };
const readCache = <T,>(key: string, fallback: T): T => { try { const raw = localStorage.getItem(`gefi:${key}`); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } };
const writeCache = (key: string, value: unknown) => localStorage.setItem(`gefi:${key}`, JSON.stringify(value));
const userCacheKey = (uid:string, key:string) => `${key}:${uid}`;
const preferredFavicon=(url:string)=>{try{const parsed=new URL(url);if((parsed.hostname==='google.com'||parsed.hostname.endsWith('.google.com'))&&parsed.pathname.startsWith('/finance'))return 'https://www.gstatic.com/finance/favicon/finance_v2_120x120.png';return `${parsed.origin}/favicon.ico`}catch{return ''}};
function QuickLinkIcon({url,name}:{url:string;name?:string}) {
 const origin=(()=>{try{return new URL(url).origin}catch{return ''}})();
 const preferred=preferredFavicon(url);
 const [source,setSource]=useState(preferred), [failed,setFailed]=useState(!preferred);
 useEffect(()=>{setSource(preferred);setFailed(!preferred)},[preferred]);
 if(failed)return <LinkIcon className="w-4 h-4 text-blue-600"/>;
 return <img src={source} alt="" aria-hidden="true" className="w-5 h-5 rounded-sm object-contain" onError={()=>{if(source.startsWith('https://www.google.com/s2/'))setFailed(true);else setSource(`https://www.google.com/s2/favicons?domain=${encodeURIComponent(origin)}&sz=64`)}} title={name?`Logo de ${name}`:'Logo del sitio'}/>;
}
const quickLinkLabel=(url:string,name?:string)=>{if(name?.trim())return name.trim();try{return new URL(url).hostname.replace(/^www\./,'')}catch{return 'Abrir acceso directo'}};
const mergeCached = <T extends {id:string}>(remote:T[], cached:T[]) => {
 const map = new Map(cached.map(item=>[item.id,item]));
 remote.forEach(item=>map.set(item.id,item));
 return [...map.values()];
};

function InvestmentSummaryCard({total,breakdown,hidden}:{total:number;breakdown:Array<{name:string;value:number}>;hidden:boolean}) {
 const [open,setOpen]=useState(false);
 const money=(value:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(value);
 return <div className="gefi-kpi group relative rounded-xl bg-white dark:bg-slate-900 border border-amber-200 dark:border-amber-900/60">
  <button type="button" aria-expanded={open} onClick={()=>setOpen(value=>!value)} className="w-full p-3 text-left"><p className="text-[10px] uppercase text-slate-400">Inversiones</p><p className="font-mono font-bold text-amber-600">{hidden?'••••':money(total)}</p><span className="mt-1 block min-h-[14px] text-[9px] font-medium text-amber-600 dark:text-amber-400">Tocá para ver detalle</span></button>
  <div className={`${open?'block':'hidden group-hover:block'} absolute z-40 right-0 top-full mt-2 w-60 rounded-xl border border-violet-200 dark:border-violet-900/60 bg-white dark:bg-slate-900 p-3 shadow-xl`}><p className="text-[10px] font-bold uppercase tracking-wide text-violet-600 dark:text-violet-400">Detalle de inversiones</p><div className="mt-2 space-y-2 text-xs">{breakdown.length?breakdown.map(item=><div key={item.name} className="flex justify-between gap-3"><span className="truncate">{item.name}</span><strong className="font-mono text-violet-600 dark:text-violet-400">{hidden?'••••':money(item.value)}</strong></div>):<p className="text-slate-400">Sin plataformas configuradas.</p>}</div></div>
 </div>;
}

export default function App() {
 const [isPageReload]=useState(()=>{const navigation=performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming|undefined;return navigation?.type==='reload'});
 const [reloadDelayDone,setReloadDelayDone]=useState(()=>!isPageReload);
 const [user,setUser]=useState<User|null>(null), [loading,setLoading]=useState(true), [txs,setTxs]=useState<Transaction[]>([]), [accounts,setAccounts]=useState<Account[]>([]), [fixed,setFixed]=useState<FixedExpense[]>([]), [loans,setLoans]=useState<Loan[]>([]), [settings,setSettings]=useState<UserSettings>(defaults), [showSettings,setShowSettings]=useState(false);
 const settingsHistoryRef=useRef(false);
 const [fixedFormOpen,setFixedFormOpen]=useState(false), [fixedDraft,setFixedDraft]=useState({nombre:'',monto:''}), [fixedFormError,setFixedFormError]=useState('');
 const [syncError,setSyncError]=useState('');
 const [isOnline,setIsOnline]=useState(()=>navigator.onLine);
 const [transferMode,setTransferMode]=useState<'toAccount'|'toCash'|null>(null);
 const [showTutorial,setShowTutorial]=useState(false), [showCurrencySetup,setShowCurrencySetup]=useState(false);
 const [showPrivacy,setShowPrivacy]=useState(false), [showHelp,setShowHelp]=useState(false), [showAccount,setShowAccount]=useState(false), [showInsights,setShowInsights]=useState(false);
 const [currentHour,setCurrentHour]=useState(()=>new Date().getHours());
 const [quickLinkMenu,setQuickLinkMenu]=useState<{id:string;x:number;y:number}|null>(null), [quickLinkEdit,setQuickLinkEdit]=useState<{id:string;nombre:string;url:string}|null>(null), [quickLinkEditError,setQuickLinkEditError]=useState(''), [quickLinkDelete,setQuickLinkDelete]=useState<string|null>(null);
 const now=new Date(); const [month,setMonth]=useState(now.getMonth()), [year,setYear]=useState(now.getFullYear());
 useEffect(()=>{if(showSettings&&!settingsHistoryRef.current){window.history.pushState({...window.history.state,gefiOverlay:'settings'},'');settingsHistoryRef.current=true;return}if(!showSettings&&settingsHistoryRef.current&&window.history.state?.gefiOverlay==='settings')window.history.back()},[showSettings]);
 useEffect(()=>{const onPopState=(event:PopStateEvent)=>{const settingsState=event.state?.gefiOverlay==='settings';settingsHistoryRef.current=settingsState;setShowSettings(settingsState)};window.addEventListener('popstate',onPopState);return()=>window.removeEventListener('popstate',onPopState)},[]);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setLoading(false);if(!u){setTxs([]);setAccounts([]);setFixed([]);setLoans([]);setSettings(defaults);return}setTxs(readCache(userCacheKey(u.uid,'transactions'),[]));setAccounts(readCache(userCacheKey(u.uid,'accounts'),[]));setFixed(readCache(userCacheKey(u.uid,'fixedExpenses'),[]));setLoans(readCache(userCacheKey(u.uid,'loans'),[]));setSettings({...defaults,...readCache<Partial<UserSettings>>(userCacheKey(u.uid,'settings'),{})});setDoc(doc(db,'users',u.uid),{email:u.email||null,displayName:u.displayName||null,updatedAt:Date.now()},{merge:true});}),[]);
 useEffect(()=>{if(!isPageReload)return;const timer=window.setTimeout(()=>setReloadDelayDone(true),1000);return()=>window.clearTimeout(timer)},[isPageReload]);
 useEffect(()=>{ document.documentElement.classList.toggle('dark',settings.darkMode); },[settings.darkMode]);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>document.documentElement.classList.toggle('reduce-motion',media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync)},[]);
 useEffect(()=>{const scale=settings.fontScale==='extraLarge'?1.25:settings.fontScale==='large'?1.12:1;document.documentElement.style.fontSize=`${scale*100}%`;return()=>{document.documentElement.style.fontSize=''}},[settings.fontScale]);
 useEffect(()=>{const language=settings.language||'es';document.documentElement.lang=language;if(language!=='en')return;return applyLanguage('en',false)},[settings.language]);
 useEffect(()=>{const timer=window.setInterval(()=>setCurrentHour(new Date().getHours()),60_000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{const update=()=>setIsOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[]);
 useEffect(()=>{if(user)writeCache(userCacheKey(user.uid,'settings'),settings)},[user,settings]);
 useEffect(()=>{if(user)writeCache(userCacheKey(user.uid,'transactions'),txs)},[user,txs]);
 useEffect(()=>{if(user)writeCache(userCacheKey(user.uid,'accounts'),accounts)},[user,accounts]);
 useEffect(()=>{if(user)writeCache(userCacheKey(user.uid,'fixedExpenses'),fixed)},[user,fixed]);
 useEffect(()=>{if(user)writeCache(userCacheKey(user.uid,'loans'),loans)},[user,loans]);
 useEffect(()=>{const limit=Date.now()-30*24*60*60*1000;const expired=txs.filter(t=>t.deletedAt&&t.deletedAt<limit);if(!expired.length)return;setTxs(current=>current.filter(t=>!expired.some(x=>x.id===t.id)));if(user)expired.filter(t=>!t.id.startsWith('local-')).forEach(t=>deleteDoc(doc(db,'users',user.uid,'transactions',t.id)).catch(()=>undefined))},[txs,user]);
 useEffect(()=>{if(!user)return; const unsubs=[
  onSnapshot(query(collection(db,'users',user.uid,'transactions'),orderBy('createdAt','desc')),s=>{setSyncError('');setTxs(current=>mergeCached(s.docs.map(d=>({id:d.id,...d.data()} as Transaction)),current.filter(x=>x.id.startsWith('local-'))))},()=>setSyncError('Sin conexión con la nube. Los cambios quedan pendientes en este dispositivo.')),
  onSnapshot(doc(db,'users',user.uid,'settings','finance'),s=>{if(s.exists()){const saved=s.data() as Partial<UserSettings>,base=saved.monedaBase||defaults.monedaBase,next={...defaults,...saved,monedaBase:base,monedas:[base,...SUPPORTED_CURRENCIES.filter(currency=>currency!==base)]} as UserSettings;setSettings(next);if(next.onboardingCompleted===false)setShowTutorial(true)}else{const next={...localizedDefaults(),onboardingCompleted:false};setSettings(next);setShowTutorial(true);setDoc(doc(db,'users',user.uid,'settings','finance'),next).catch(()=>undefined)}},()=>console.warn('Firestore no disponible: se conserva el respaldo local.')),
  onSnapshot(collection(db,'users',user.uid,'accounts'),s=>setAccounts(current=>mergeCached(s.docs.map(d=>({id:d.id,...d.data()} as Account)),current.filter(x=>x.id.startsWith('local-')))),()=>undefined),
  onSnapshot(collection(db,'users',user.uid,'fixedExpenses'),s=>setFixed(current=>mergeCached(s.docs.map(d=>({id:d.id,...d.data()} as FixedExpense)),current.filter(x=>x.id.startsWith('local-')))),()=>undefined),
  onSnapshot(collection(db,'users',user.uid,'loans'),s=>setLoans(current=>mergeCached(s.docs.map(d=>({id:d.id,...d.data()} as Loan)),current.filter(x=>x.id.startsWith('local-')))),()=>undefined)]; return()=>unsubs.forEach(x=>x());},[user]);
 useEffect(()=>{if(!user)return;const pending=txs.filter(item=>item.id.startsWith('local-'));pending.forEach(item=>{const cloudId=item.id.replace(/^local-/,'')||crypto.randomUUID(),cloudItem={...item,id:cloudId,uid:user.uid};setDoc(doc(db,'users',user.uid,'transactions',cloudId),cloudItem).then(()=>{setSyncError('');setTxs(current=>current.map(existing=>existing.id===item.id?cloudItem:existing))}).catch(()=>setSyncError('Sin conexión con la nube. Los cambios quedan pendientes en este dispositivo.'))})},[user,txs]);
 const saveSettings=async(next:UserSettings)=>{setSettings(next);window.dispatchEvent(new CustomEvent('gefi:currency-preference',{detail:next.monedaBase}));if(user) await setDoc(doc(db,'users',user.uid,'settings','finance'),next).catch(()=>undefined)};
 const resetAllData=async()=>{if(!user)throw new Error('No hay una cuenta activa.');for(const name of ['transactions','accounts','fixedExpenses','loans']){const snapshot=await getDocs(collection(db,'users',user.uid,name));await Promise.all(snapshot.docs.map(item=>deleteDoc(item.ref)))}setTxs([]);setAccounts([]);setFixed([]);setLoans([]);await saveSettings({...defaults,onboardingCompleted:true});};
 const removeAccount=async()=>{if(!user)throw new Error('No hay una cuenta activa.');await resetAllData();await deleteDoc(doc(db,'users',user.uid)).catch(()=>undefined);await deleteUser(user);};
 const completeTutorial=()=>{setShowTutorial(false);if(settings.currencySetupCompleted===false)setShowCurrencySetup(true);void saveSettings({...settings,onboardingCompleted:true})};
 const saveQuickLinkEdit=()=>{if(!quickLinkEdit)return;const url=quickLinkEdit.url.trim();if(!/^https?:\/\//.test(url)){setQuickLinkEditError('La URL debe comenzar con http:// o https://.');return}saveSettings({...settings,quickLinks:settings.quickLinks.map(x=>x.id===quickLinkEdit.id?{...x,nombre:quickLinkEdit.nombre.trim(),url}:x)});setQuickLinkEdit(null);setQuickLinkEditError('')};
 const currentTxs=useMemo(()=>{const seen=new Set<string>();return txs.filter(t=>!t.deletedAt&&Number.isFinite(t.monto)&&t.monto>0&&!/\bundefined\b/i.test(t.motivo||'')&&(t.motivo||'').trim()!=='Restauración del saldo anterior').filter(t=>{const key=JSON.stringify([t.fecha,t.categoria,Number(t.monto),t.moneda||'ARS',Number(t.cotizacion||1),(t.motivo||'').trim(),(t.categoriaDetalle||'').trim(),t.cuentaOrigen||'',t.cuentaDestino||'']);if(seen.has(key))return false;seen.add(key);return true})},[txs]);
 const trashedTxs=useMemo(()=>txs.filter(t=>Boolean(t.deletedAt)).sort((a,b)=>(b.deletedAt||0)-(a.deletedAt||0)),[txs]);
 const active=useMemo(()=>currentTxs.filter(t=>{const d=new Date(`${t.fecha}T12:00:00`);return d.getFullYear()===year&&d.getMonth()===month}),[currentTxs,year,month]);
 const categorySpent=useMemo(()=>active.filter(t=>!isBalanceCorrection(t)&&(t.categoria==='Gasto'||t.categoria==='Gasto efectivo'||t.categoria==='Ef-')).reduce<Record<string,number>>((totals,t)=>{const category=t.categoriaDetalle||'General';totals[category]=(totals[category]||0)+toArs(t);return totals},{}),[active]);
 const savingsTotal=useMemo(()=>currentTxs.filter(t=>t.categoria==='Ahorro').reduce((total,t)=>total+toArs(t),0),[currentTxs]);
 const investmentTransactions=useMemo(()=>currentTxs.filter(transaction=>{if(transaction.categoria!=='Inversion'&&transaction.categoria!=='Desinversion')return false;const date=new Date(`${transaction.fecha}T12:00:00`);return date.getFullYear()<year||(date.getFullYear()===year&&date.getMonth()<=month)}),[currentTxs,month,year]);
 const investmentBalance=useMemo(()=>[...investmentTransactions].sort((a,b)=>a.fecha.localeCompare(b.fecha)||(a.createdAt||0)-(b.createdAt||0)).reduce((total,transaction)=>Number.isFinite(transaction.balanceTarget)?Number(transaction.balanceTarget):total+(transaction.categoria==='Desinversion'?-toArs(transaction):toArs(transaction)),0),[investmentTransactions]);
 const summary=useMemo(()=>{
  let income=0,expense=0,investment=0,cumulativeIncome=0,cumulativeExpense=0,cashMovements=0;
  currentTxs.forEach(t=>{const value=toArs(t),date=new Date(`${t.fecha}T12:00:00`),isCurrent=date.getFullYear()===year&&date.getMonth()===month,isBefore=date.getFullYear()<year||(date.getFullYear()===year&&date.getMonth()<month);if(!isCurrent&&!isBefore)return;
   if(t.categoria==='Ingreso'||t.categoria==='Ef+')cumulativeIncome+=value;
   const correction=isBalanceCorrection(t);
   if(!correction&&(t.categoria==='Gasto'||t.categoria==='Ef-'||t.categoria==='Gasto efectivo'))cumulativeExpense+=value;
   cashMovements+=cashImpact(t,accounts);
   if(isCurrent){if(!correction&&(t.categoria==='Ingreso'||t.categoria==='Ef+'))income+=value;if(!correction&&(t.categoria==='Gasto'||t.categoria==='Ef-'||t.categoria==='Gasto efectivo'))expense+=value;if(!correction&&t.categoria==='Inversion')investment+=value;if(!correction&&t.categoria==='Desinversion')investment-=value;}
  });
  const spent=active.filter(t=>!isBalanceCorrection(t)&&(t.categoria==='Gasto'||t.categoria==='Gasto efectivo')).map(toArs),cash=accounts.filter(a=>a.tipo==='Efectivo').reduce((n,a)=>n+Number(a.saldoInicial||0),0)+cashMovements;
  const hasHistoricalBalance=txs.some(item=>item.balanceOrigin==='baseline'||item.balanceOrigin===undefined),accountBalance=(hasHistoricalBalance?18537.08:0)+txs.reduce((total,item)=>total+Number(item.accountDelta||0),0);
  return {income,expense,investment:investmentBalance,investmentThisMonth:investment,patrimonio:accountBalance+cash+investmentBalance,cash,max:Math.max(0,...spent),accounts:accountBalance};
 },[currentTxs,active,accounts,month,year,txs,investmentBalance]);
 const investmentBreakdown=useMemo(()=>{const configured=settings.investmentPlatforms||[];const values=new Map<string,number>(configured.map(name=>[name,0]));[...investmentTransactions].sort((a,b)=>a.fecha.localeCompare(b.fecha)||(a.createdAt||0)-(b.createdAt||0)).forEach(transaction=>{const text=`${transaction.categoriaDetalle||''} ${transaction.motivo||''}`;const platform=configured.find(name=>text.toLowerCase().includes(name.toLowerCase()))||( /binance|bitcoin|ethereum|ether|xrp|cripto/i.test(text)?configured.find(name=>/binance/i.test(name)):undefined )||configured[0]||'Sin plataforma';if(Number.isFinite(transaction.balanceTarget)){const current=[...values.values()].reduce((sum,value)=>sum+value,0);values.set(platform,(values.get(platform)||0)+Number(transaction.balanceTarget)-current);return}values.set(platform,(values.get(platform)||0)+(transaction.categoria==='Desinversion'?-toArs(transaction):toArs(transaction)))});return [...values.entries()].map(([name,value])=>({name,value:Math.max(0,value)})).filter(item=>item.value>0||configured.includes(item.name))},[investmentTransactions,settings.investmentPlatforms]);
 const addTx=async(data:Omit<Transaction,'id'|'createdAt'|'uid'>)=>{if(!user||!data.fecha||data.monto<=0||!SUPPORTED_CURRENCIES.includes((data.moneda||'ARS') as typeof SUPPORTED_CURRENCIES[number]))throw new Error('Completá fecha, importe y moneda.'); if(data.categoria==='Transferencia'&&(!data.cuentaOrigen||!data.cuentaDestino||data.cuentaOrigen===data.cuentaDestino))throw new Error('Elegí una cuenta de origen y otra de destino. Una transferencia no es un gasto.'); const id=crypto.randomUUID(), next:Transaction={...data,motivo:(data.motivo||'').trim(),id,createdAt:Date.now(),uid:user.uid,accountDelta:accountImpact(data as Transaction,accounts),balanceOrigin:'new'}; setTxs(prev=>[next,...prev]); try { await setDoc(doc(db,'users',user.uid,'transactions',id),next);setSyncError(''); } catch { setSyncError('Sin conexión con la nube. El movimiento quedó pendiente en este dispositivo.');setTxs(prev=>prev.map(x=>x.id===id?{...x,id:`local-${id}`}:x)); }};
 const deleteTx=async(id:string)=>{const item=txs.find(x=>x.id===id);if(!item)return;const deletedAt=Date.now(),balanceOrigin=item.balanceOrigin||'baseline',accountDelta=balanceOrigin==='new'?0:Number(item.accountDelta||0)-accountImpact(item,accounts);setTxs(prev=>prev.map(x=>x.id===id?{...x,deletedAt,balanceOrigin,accountDelta}:x));if(!id.startsWith('local-'))await setDoc(doc(db,'users',user.uid,'transactions',id),{deletedAt,balanceOrigin,accountDelta},{merge:true}).catch(()=>undefined)};
 const restoreTx=async(id:string)=>{const item=txs.find(x=>x.id===id);if(!item)return;const balanceOrigin=item.balanceOrigin||'baseline',accountDelta=balanceOrigin==='new'?accountImpact(item,accounts):0;setTxs(prev=>prev.map(x=>x.id===id?{...x,deletedAt:undefined,balanceOrigin,accountDelta}:x));if(!id.startsWith('local-'))await setDoc(doc(db,'users',user.uid,'transactions',id),{deletedAt:null,balanceOrigin,accountDelta},{merge:true}).catch(()=>undefined)};
 const permanentlyDeleteTx=async(id:string)=>{setTxs(prev=>prev.filter(x=>x.id!==id));if(!id.startsWith('local-'))await deleteDoc(doc(db,'users',user.uid,'transactions',id)).catch(()=>undefined)};
 const editTx=async(next:Transaction)=>{const previous=txs.find(x=>x.id===next.id),balanceOrigin=previous?.balanceOrigin||'baseline',accountDelta=balanceOrigin==='new'?accountImpact(next,accounts):Number(previous?.accountDelta||0)+accountImpact(next,accounts)-accountImpact(previous||next,accounts),updated={...next,balanceOrigin,accountDelta};setTxs(prev=>prev.map(x=>x.id===next.id?updated:x));if(!next.id.startsWith('local-'))await setDoc(doc(db,'users',user.uid,'transactions',next.id),updated,{merge:true}).catch(()=>undefined)};
 const exportAll=()=>{if(!user)return; const body={exportedAt:new Date().toISOString(),profile:{displayName:user.displayName,email:user.email},settings,accounts,categories:settings.categorias,fixedExpenses:fixed,quickLinks:settings.quickLinks,loans,investments:txs.filter(t=>t.categoria==='Inversion'),transactions:txs}; const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'application/json'}));a.download=`gefi-respaldo-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
 const importBackup=async(file:File)=>{if(!user)throw new Error('Iniciá sesión para importar un respaldo.');if(file.size>10*1024*1024)throw new Error('El respaldo supera el tamaño máximo de 10 MB.');let data:Record<string,unknown>;try{data=JSON.parse(await file.text())}catch{throw new Error('El archivo no contiene un JSON válido.')}const importedTxs=Array.isArray(data.transactions)?data.transactions.filter(item=>item&&typeof item==='object'&&typeof (item as Transaction).id==='string').map(item=>({...item as Transaction,uid:user.uid})):[],importedAccounts=Array.isArray(data.accounts)?data.accounts.filter(item=>item&&typeof item==='object'&&typeof (item as Account).id==='string') as Account[]:[],importedFixed=Array.isArray(data.fixedExpenses)?data.fixedExpenses.filter(item=>item&&typeof item==='object'&&typeof (item as FixedExpense).id==='string') as FixedExpense[]:[],importedLoans=Array.isArray(data.loans)?data.loans.filter(item=>item&&typeof item==='object'&&typeof (item as Loan).id==='string') as Loan[]:[],importedSettings=data.settings&&typeof data.settings==='object'?{...defaults,...data.settings as Partial<UserSettings>}:null;if(!importedTxs.length&&!importedAccounts.length&&!importedFixed.length&&!importedLoans.length&&!importedSettings)throw new Error('No encontré datos de GeFi para importar.');await Promise.all([...importedTxs.map(item=>setDoc(doc(db,'users',user.uid,'transactions',item.id),item)),...importedAccounts.map(item=>setDoc(doc(db,'users',user.uid,'accounts',item.id),item)),...importedFixed.map(item=>setDoc(doc(db,'users',user.uid,'fixedExpenses',item.id),item)),...importedLoans.map(item=>setDoc(doc(db,'users',user.uid,'loans',item.id),item)),...(importedSettings?[setDoc(doc(db,'users',user.uid,'settings','finance'),importedSettings)]:[])]);setTxs(current=>mergeCached(importedTxs,current));setAccounts(current=>mergeCached(importedAccounts,current));setFixed(current=>mergeCached(importedFixed,current));setLoans(current=>mergeCached(importedLoans,current));if(importedSettings)setSettings(importedSettings);setSyncError('Respaldo importado correctamente.');};
 if(loading||!reloadDelayDone)return <div className="min-h-screen grid place-items-center bg-gradient-to-r from-slate-950 to-blue-950 text-white"><div className="flex flex-col items-center gap-4"><img src="/Gestor-Financiero/favicon.svg" alt="Logo de Gestor Financiero" className="h-20 w-20 rounded-2xl shadow-2xl shadow-blue-500/30"/><span className="text-xl font-bold">Gestor Financiero</span>{isPageReload&&<span aria-label="Actualizando" className="h-6 w-6 animate-spin rounded-full border-2 border-blue-200/40 border-t-white"/>}</div></div>;
 if(!user)return <Login onLoginSuccess={()=>{}} darkMode={settings.darkMode} onToggleDarkMode={()=>saveSettings({...settings,darkMode:!settings.darkMode})}/>;
 const addAccount=async(data?:{nombre:string;tipo:Account['tipo'];saldoInicial:number})=>{let values=data;if(!values){const nombre=prompt('Nombre de la cuenta');if(!nombre?.trim())return;const rawTipo=prompt('Tipo: Banco, Billetera o Efectivo','Banco')||'Banco';const saldo=Number(prompt('Saldo inicial (en moneda de la cuenta)','0'));values={nombre:nombre.trim(),tipo:(['Banco','Billetera','Efectivo'].includes(rawTipo)?rawTipo:'Banco') as Account['tipo'],saldoInicial:isFinite(saldo)?saldo:0}}const id=crypto.randomUUID(), account:Account={id,nombre:values.nombre.trim(),tipo:values.tipo,moneda:settings.monedaBase,saldoInicial:values.saldoInicial,activa:true};setAccounts(p=>[...p,account]);try{await setDoc(doc(db,'users',user.uid,'accounts',id),account)}catch{setAccounts(p=>p.map(x=>x.id===id?{...x,id:`local-${id}`}:x))}};
 const deleteAccount=async(id:string)=>{setAccounts(p=>p.filter(x=>x.id!==id));if(!id.startsWith('local-'))await deleteDoc(doc(db,'users',user.uid,'accounts',id)).catch(()=>undefined)};
 const addFixed=async(data?:{nombre:string;monto:number})=>{if(!data||typeof data.nombre!=='string'||!data.nombre.trim()||!Number.isFinite(data.monto)||data.monto<=0){setFixedFormError('');setFixedFormOpen(true);return}const expense:FixedExpense={id:`local-${crypto.randomUUID()}`,nombre:data.nombre.trim(),monto:data.monto,moneda:settings.monedaBase,categoria:'General',cuentaId:accounts[0]?.id||'',frecuencia:'Mensual',proximoVencimiento:today(),estado:'Pendiente'};setFixed(p=>[...p,expense]);setFixedDraft({nombre:'',monto:''});setFixedFormOpen(false);try{await addDoc(collection(db,'users',user.uid,'fixedExpenses'),{...expense,id:undefined})}catch{}};
 const deleteFixed=async(id:string)=>{setFixed(p=>p.filter(x=>x.id!==id));if(!id.startsWith('local-')) await deleteDoc(doc(db,'users',user.uid,'fixedExpenses',id)).catch(()=>undefined)};
 const addLoan=async(data?:{persona:string;monto:number;motivo:string;cuentaId:string})=>{if(!data||typeof data.persona!=='string'||!data.persona.trim()||!Number.isFinite(data.monto)||data.monto<=0){setShowSettings(true);return}const values=data;const loan:Loan={id:`local-${crypto.randomUUID()}`,persona:values.persona.trim(),monto:values.monto,moneda:settings.monedaBase,motivo:values.motivo||'',fecha:today(),estado:'Pendiente',cuentaId:values.cuentaId||'',pagos:[]};setLoans(p=>[...p,loan]);await addTx({fecha:today(),categoria:'Prestamo',monto:values.monto,moneda:settings.monedaBase,cotizacion:1,motivo:`Préstamo a ${values.persona.trim()}${values.motivo?` · ${values.motivo}`:''}`,categoriaDetalle:'Préstamo realizado',cuentaOrigen:values.cuentaId||''});try{await addDoc(collection(db,'users',user.uid,'loans'),{...loan,id:undefined})}catch{}};
 const deleteLoan=async(id:string)=>{setLoans(p=>p.filter(x=>x.id!==id));if(!id.startsWith('local-')) await deleteDoc(doc(db,'users',user.uid,'loans',id)).catch(()=>undefined)};
 const markLoanPaid=async(loan:Loan)=>{if(loan.estado==='Pagado')return;const paidAt=today();const updated={...loan,estado:'Pagado' as const,pagos:[...loan.pagos,{fecha:paidAt,monto:loan.monto,nota:'Devolución total'}]};setLoans(p=>p.map(x=>x.id===loan.id?updated:x)); await addTx({fecha:paidAt,categoria:'Prestamo',monto:loan.monto,moneda:loan.moneda,cotizacion:1,motivo:`Devolución de préstamo · ${loan.persona}`,categoriaDetalle:'Devolución de préstamo',cuentaDestino:loan.cuentaId});if(!loan.id.startsWith('local-'))await updateDoc(doc(db,'users',user.uid,'loans',loan.id),{estado:'Pagado',pagos:updated.pagos}).catch(()=>undefined)};
 const correctBalance=async(kind:'accounts'|'cash'|'patrimony'|'investment',target:number)=>{const current=kind==='accounts'?summary.accounts:kind==='cash'?summary.cash:kind==='investment'?summary.investment:summary.patrimonio;const difference=Number((target-current).toFixed(2));if(Math.abs(difference)<0.01)return;const day=Math.min(new Date().getDate(),new Date(year,month+1,0).getDate());const fecha=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const categoria=kind==='cash'?(difference>0?'Ef+':'Ef-'):kind==='investment'?(difference>0?'Inversion':'Desinversion'):(difference>0?'Ingreso':'Gasto');await addTx({fecha,categoria,monto:Math.abs(difference),moneda:'ARS',cotizacion:1,motivo:`Corrección de ${kind==='accounts'?'dinero en cuenta':kind==='cash'?'efectivo':kind==='investment'?'inversiones':'patrimonio total'}`,categoriaDetalle:'Corrección de saldo',...(kind==='investment'?{balanceTarget:target}:{})});};
 const groupedLoans=(()=>{const all=loans.filter(loan=>loan&&typeof loan.persona==='string'&&loan.persona.trim()&&loan.persona.trim().toLowerCase()!=='undefined'&&Number.isFinite(loan.monto)&&loan.monto>0);currentTxs.filter(t=>t.categoria==='Prestamo'&&!t.cuentaDestino).forEach(t=>{const text=(t.motivo||'').replace(/^Préstamo a\s+/i,''),persona=text.split('·')[0].trim()||'Sin especificar';if(persona.toLowerCase()==='undefined'||!Number.isFinite(t.monto)||t.monto<=0)return;if(!all.some(l=>l.persona.toLowerCase()===persona.toLowerCase()&&l.fecha===t.fecha&&Math.abs(l.monto-t.monto)<0.01))all.push({id:`tx-${t.id}`,persona,monto:t.monto,moneda:t.moneda||'ARS',motivo:text.split('·').slice(1).join('·').trim()||t.categoriaDetalle||'Préstamo',fecha:t.fecha,estado:'Pendiente',cuentaId:t.cuentaOrigen,pagos:[]})});const groups=new Map<string,Loan[]>();all.forEach(loan=>{const key=loan.persona.trim().toLowerCase();groups.set(key,[...(groups.get(key)||[]),loan])});return [...groups.values()]})();
 const totalLoanDebt=groupedLoans.flat().reduce((sum,loan)=>sum+(loan.estado==='Pendiente'?Number(loan.monto||0):0),0);
 const savings=active.filter(t=>t.categoria==='Ahorro');
 const greeting=currentHour>=5&&currentHour<12?'Buenos días':currentHour>=12&&currentHour<20?'Buenas tardes':'Buenas noches';
 const monthName=new Intl.DateTimeFormat(settings.language==='en'?'en-US':'es-AR',{month:'long'}).format(new Date(year,month,1)).toUpperCase();
 const summaryPrefix=settings.language==='en'?'SUMMARY FOR':'RESUMEN DE';
 const displayName=(user.displayName||user.email?.split('@')[0]||'usuario').trim().split(/\s+/).slice(0,2).join(' ');
  return <div className="gefi-shell min-h-[100dvh] overflow-x-hidden text-slate-800 dark:text-slate-100"><Header user={user} selectedMonth={month} selectedYear={year} onMonthChange={setMonth} onYearChange={setYear} onLogout={()=>signOut(auth)} darkMode={settings.darkMode} onToggleDarkMode={()=>saveSettings({...settings,darkMode:!settings.darkMode})} hideBalances={settings.hideBalances} onToggleHideBalances={()=>saveSettings({...settings,hideBalances:!settings.hideBalances})} onOpenSettings={()=>setShowSettings(true)} onOpenAccount={()=>setShowAccount(true)}/><main className="gefi-main mx-auto max-w-7xl px-3 sm:px-6">
 <div className="gefi-welcome mb-4 flex flex-col gap-4 rounded-2xl p-4 text-white sm:mb-5 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="relative z-10 min-w-0"><p className="text-[11px] font-medium text-blue-200 sm:text-xs">{summaryPrefix} {monthName} {year}</p><h2 className="break-words text-xl font-semibold tracking-tight sm:text-2xl">{greeting}, {displayName}.</h2></div><button onClick={()=>setShowSettings(true)} className="relative z-10 min-h-10 w-full rounded-lg border border-blue-200/50 bg-white/10 px-3 py-2 text-xs font-semibold text-white hover:bg-white/15 sm:w-auto">Configuración</button></div>
 {syncError&&<div role="alert" className="mb-4 rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-xs font-medium text-amber-800 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-300">{syncError}</div>}
  {!isOnline&&<div role="status" className="mb-4 rounded-xl border border-violet-300 bg-violet-50 px-4 py-3 text-xs font-medium text-violet-800 dark:border-violet-800 dark:bg-violet-950/30 dark:text-violet-200">Estás sin conexión. Podés seguir usando GeFi: los cambios se sincronizarán cuando vuelva Internet.</div>}
  {isOnline&&!syncError&&<p role="status" className="mb-4 flex items-center gap-2 text-[11px] font-medium text-emerald-600 dark:text-emerald-400"><span className="h-2 w-2 rounded-full bg-emerald-500"/>Cambios sincronizados</p>}
  <div className="mb-6"><SmartTransactionInput accounts={accounts} categories={settings.categorias} investmentPlatforms={settings.investmentPlatforms||[]} currency={settings.monedaBase} language={settings.language||'es'} onAddTransaction={addTx}/></div>
  <div className="mb-6 flex justify-end"><button type="button" onClick={()=>setShowInsights(true)} className="rounded-xl border border-blue-200 bg-white px-4 py-2 text-xs font-bold text-blue-700 shadow-sm dark:border-blue-900/60 dark:bg-slate-900 dark:text-blue-300">Ver presupuestos y reportes</button></div>
 <section className="gefi-kpi-grid grid grid-cols-2 gap-3 mb-6 lg:grid-cols-7">{[['Patrimonio total',summary.patrimonio,'text-blue-700'],['En cuentas',summary.accounts,'text-blue-700'],['Efectivo',summary.cash,'text-cyan-700'],['Ingresos',summary.income,'text-emerald-600'],['Gastos',summary.expense,'text-rose-600'],['Mayor gasto',summary.max,'text-rose-600']].map(([l,v,c])=>{const isTransfer=String(l)==='En cuentas'||String(l)==='Efectivo';return <button key={String(l)} type="button" onClick={()=>isTransfer&&setTransferMode(String(l)==='En cuentas'?'toCash':'toAccount')} className={`gefi-kpi flex flex-col p-3 text-left border transition ${isTransfer?'cursor-pointer focus:outline-none focus:ring-2 focus:ring-blue-400/50':''}`} title={isTransfer?'Mover dinero entre efectivo y cuenta':''}><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">{l}</p><p className={`mt-1 font-mono text-[15px] font-semibold tracking-tight ${c}`}>{settings.hideBalances?'••••':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v))}</p><span className={`mt-auto block min-h-[14px] pt-2 text-[9px] font-medium ${isTransfer?'text-blue-600 dark:text-blue-400':'invisible'}`}>{isTransfer?'Tocá para transferir':'Espacio reservado'}</span></button>})}<InvestmentSummaryCard total={summary.investment} breakdown={investmentBreakdown} hidden={settings.hideBalances}/></section>
 <div className="grid lg:grid-cols-12 gap-6"><div className="lg:col-span-4 space-y-5"><TransactionForm onAddTransaction={addTx} selectedMonth={month} selectedYear={year} accounts={accounts} currencies={settings.monedas} categories={settings.categorias} investmentPlatforms={settings.investmentPlatforms||[]}/><section className="rounded-2xl p-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><div className="flex justify-between"><h3 className="font-bold text-sm">Gastos fijos</h3><button title="Agregar gasto fijo" onClick={addFixed}><Plus className="w-4 h-4 text-blue-600"/></button></div>{fixed.map(f=><div key={f.id} className="text-xs mt-2 flex items-center justify-between gap-2"><span>{f.nombre} · {f.proximoVencimiento}</span><span className="flex gap-2"><button className="text-emerald-600" onClick={()=>addTx({fecha:today(),categoria:'Gasto',monto:f.monto,moneda:f.moneda,cotizacion:1,motivo:f.nombre,categoriaDetalle:f.categoria,cuentaOrigen:f.cuentaId})}>Pagar</button><button className="text-rose-600" onClick={()=>confirm(`¿Eliminar ${f.nombre}?`)&&deleteFixed(f.id)}>Eliminar</button></span></div>)}</section></div><div className="lg:col-span-8"><TransactionList transactions={active} accounts={accounts} loading={false} hideBalances={settings.hideBalances} onDeleteTransaction={deleteTx} onEditTransaction={editTx}/></div></div>
 <div className="mt-6"><SavingsGoalsPanel goals={settings.savingsGoals||[]} saved={savingsTotal} hidden={settings.hideBalances} onChange={savingsGoals=>void saveSettings({...settings,savingsGoals})}/></div>
 <div className="mt-6"><PaymentCalendar reminders={settings.paymentReminders||[]} currency={settings.monedaBase} language={settings.language||'es'} hidden={settings.hideBalances} onChange={paymentReminders=>void saveSettings({...settings,paymentReminders})}/></div>
 <section className="mt-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-5">
  <div className="flex flex-wrap justify-between items-center gap-3 mb-3"><div><h3 className="font-bold text-sm">Préstamos realizados</h3><p className="text-[11px] text-slate-400">Los préstamos de una misma persona se agrupan. Abrí cada grupo para consultar el detalle.</p></div><button onClick={addLoan} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Prestar dinero</button></div>
  <div className="mb-3 flex items-center justify-between gap-3 rounded-xl border border-amber-200 bg-gradient-to-r from-amber-50 to-orange-50 p-3 dark:border-amber-900/60 dark:from-amber-950/30 dark:to-orange-950/20"><div><p className="text-[10px] font-bold uppercase tracking-wide text-amber-700 dark:text-amber-400">Total que te deben</p><p className="text-[10px] text-slate-500 dark:text-slate-400">Suma de todos los préstamos pendientes</p></div><strong className="font-mono text-base text-amber-700 dark:text-amber-400">{new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(totalLoanDebt)}</strong></div>
  {groupedLoans.length===0?<p className="text-xs text-slate-400 py-3">Todavía no registraste préstamos.</p>:<div className="space-y-2">{groupedLoans.map(group=>{const person=group[0].persona,total=group.reduce((sum,loan)=>sum+(loan.estado==='Pendiente'?loan.monto:0),0);return <details key={person.toLowerCase()} className="rounded-xl bg-slate-50 dark:bg-slate-950 p-3"><summary className="cursor-pointer list-none flex items-center justify-between gap-3 text-xs"><strong>{person}</strong><span className="font-mono font-bold text-amber-600">Total pendiente: {new Intl.NumberFormat('es-AR',{style:'currency',currency:group[0].moneda||'ARS'}).format(total)}</span></summary><div className="mt-3 space-y-2 border-t border-slate-200 dark:border-slate-800 pt-3">{group.sort((a,b)=>a.fecha.localeCompare(b.fecha)).map(loan=><div key={loan.id} className="flex flex-wrap items-center justify-between gap-2 text-xs"><div><span className="font-mono text-slate-400">{loan.fecha}</span><span className="ml-2">{loan.motivo||'Sin detalle'} · {new Intl.NumberFormat('es-AR',{style:'currency',currency:loan.moneda||'ARS'}).format(loan.monto)}</span></div><div className="flex gap-2"><span className={loan.estado==='Pagado'?'text-emerald-600':'text-amber-600'}>{loan.estado}</span>{loan.estado==='Pendiente'&&<button onClick={()=>markLoanPaid(loan)} className="font-bold text-emerald-600">Marcar pagado</button>}<button onClick={()=>confirm(`¿Eliminar este préstamo a ${loan.persona}?`)&&deleteLoan(loan.id)} className="text-rose-600">Eliminar</button></div></div>)}</div></details>})}</div>}
 </section>
 {settings.showSavings!==false&&<section className="mt-6 rounded-2xl bg-white dark:bg-slate-900 border border-violet-200 dark:border-violet-900/60 p-5"><h3 className="font-bold text-sm">Ahorros</h3><p className="text-[11px] text-slate-400 mt-1">Ahorros del mes seleccionado. Podés ocultar esta sección desde Configuración.</p>{savings.length===0?<p className="py-3 text-xs text-slate-400">No hay ahorros registrados este mes.</p>:<div className="mt-3 space-y-2">{savings.map(item=><div key={item.id} className="flex justify-between rounded-xl bg-violet-50 dark:bg-violet-950/20 p-3 text-xs"><span>{item.fecha} · {item.motivo}</span><strong className="font-mono text-violet-600">{new Intl.NumberFormat('es-AR',{style:'currency',currency:item.moneda||'ARS'}).format(item.monto)}</strong></div>)}</div>}</section>}
 </main><footer className="border-t border-slate-200 bg-white/70 dark:border-slate-800 dark:bg-slate-900/70"><div className="mx-auto max-w-7xl px-4 py-4">{settings.quickLinks.length>0&&<><p className="mb-2 text-center text-[10px] uppercase tracking-wider text-slate-400">Accesos directos · clic derecho para editar</p><div className="flex flex-wrap items-center justify-center gap-2">{settings.quickLinks.map(link=>{const label=quickLinkLabel(link.url,link.nombre);return <a key={link.id} href={link.url} target="_blank" rel="noreferrer" aria-label={label} title={label} onContextMenu={e=>{e.preventDefault();setQuickLinkMenu({id:link.id,x:Math.min(e.clientX,window.innerWidth-180),y:Math.min(e.clientY,window.innerHeight-110)})}} className={`flex items-center justify-center gap-2 text-xs font-medium rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 ${link.nombre?.trim()?'px-3 py-2':'w-10 h-10'}`}><QuickLinkIcon url={link.url} name={link.nombre}/>{link.nombre?.trim()&&<><span>{link.nombre.trim()}</span><ExternalLink className="w-3 h-3 text-slate-400"/></>}</a>})}</div></>}<p className="mt-3 text-center text-xs text-slate-400"><button type="button" onClick={()=>setShowPrivacy(true)} className="font-medium text-blue-600 hover:underline dark:text-blue-400">Política de privacidad</button><span className="mx-2 text-slate-300">·</span><button type="button" onClick={()=>setShowHelp(true)} className="font-medium text-blue-600 hover:underline dark:text-blue-400">Ayuda</button><span className="mx-2 text-slate-300">·</span><a className="font-medium text-blue-600 hover:underline dark:text-blue-400" href="mailto:gefisupport@gmail.com">Soporte: gefisupport@gmail.com</a></p></div></footer>
 {quickLinkMenu&&<><button aria-label="Cerrar menú" className="fixed inset-0 z-[69] cursor-default" onClick={()=>setQuickLinkMenu(null)}/><div role="menu" className="fixed z-[70] w-44 overflow-hidden rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 shadow-xl p-1" style={{left:quickLinkMenu.x,top:quickLinkMenu.y}}>{(()=>{const link=settings.quickLinks.find(x=>x.id===quickLinkMenu.id);if(!link)return null;return <><button role="menuitem" onClick={()=>{setQuickLinkEditError('');setQuickLinkEdit({id:link.id,nombre:link.nombre||'',url:link.url});setQuickLinkMenu(null)}} className="w-full flex items-center gap-2 rounded-lg px-3 py-2 text-left text-xs hover:bg-slate-100 dark:hover:bg-slate-800"><Pencil className="w-3.5 h-3.5 text-blue-600"/>Modificar acceso</button><button role="menuitem" onClick={()=>{setQuickLinkDelete(link.id);setQuickLinkMenu(null)}} className="w-full flex items-center gap-2 rounded-lg px-3 py-2 text-left text-xs text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/30"><Trash2 className="w-3.5 h-3.5"/>Eliminar acceso</button></>})()}</div></>}
 {quickLinkEdit&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-sm rounded-2xl bg-white dark:bg-slate-900 p-6 shadow-2xl"><h3 className="font-bold">Modificar acceso directo</h3><p className="mt-1 text-xs text-slate-400">El nombre es opcional; la URL es obligatoria.</p><label className="block mt-4 text-xs text-slate-500 dark:text-slate-400">Nombre<input autoFocus value={quickLinkEdit.nombre} onChange={e=>setQuickLinkEdit({...quickLinkEdit,nombre:e.target.value})} placeholder="Nombre opcional" className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 p-2.5 text-sm text-slate-900 dark:text-slate-100"/></label><label className="block mt-3 text-xs text-slate-500 dark:text-slate-400">URL<input value={quickLinkEdit.url} onChange={e=>{setQuickLinkEditError('');setQuickLinkEdit({...quickLinkEdit,url:e.target.value})}} onKeyDown={e=>e.key==='Enter'&&saveQuickLinkEdit()} placeholder="https://ejemplo.com" className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 p-2.5 text-sm text-slate-900 dark:text-slate-100"/></label>{quickLinkEditError&&<p className="mt-3 rounded-lg bg-rose-50 dark:bg-rose-950/30 p-2.5 text-xs text-rose-600 dark:text-rose-300">{quickLinkEditError}</p>}<div className="flex justify-end gap-2 mt-5"><button onClick={()=>{setQuickLinkEdit(null);setQuickLinkEditError('')}} className="rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2 text-xs font-bold">Cancelar</button><button onClick={saveQuickLinkEdit} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white">Guardar cambios</button></div></div></div>}
 {quickLinkDelete&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-sm rounded-2xl bg-white dark:bg-slate-900 p-6 shadow-2xl"><h3 className="font-bold">Eliminar acceso directo</h3><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">¿Querés quitar <strong className="text-slate-800 dark:text-slate-100">{quickLinkLabel(settings.quickLinks.find(x=>x.id===quickLinkDelete)?.url||'',settings.quickLinks.find(x=>x.id===quickLinkDelete)?.nombre)}</strong> de tus accesos directos?</p><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setQuickLinkDelete(null)} className="rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2 text-xs font-bold">Cancelar</button><button onClick={()=>{saveSettings({...settings,quickLinks:settings.quickLinks.filter(x=>x.id!==quickLinkDelete)});setQuickLinkDelete(null)}} className="rounded-lg bg-rose-600 px-4 py-2 text-xs font-bold text-white">Sí, eliminar</button></div></div></div>}
 {fixedFormOpen&&<div className="fixed inset-0 z-[85] grid place-items-center bg-slate-950/60 p-4" onMouseDown={e=>e.target===e.currentTarget&&setFixedFormOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby="fixed-title" className="w-full max-w-sm rounded-2xl bg-white dark:bg-slate-900 p-6 shadow-2xl border border-slate-200 dark:border-slate-700"><div className="flex items-center justify-between"><div><h3 id="fixed-title" className="font-bold">Agregar gasto fijo</h3><p className="mt-1 text-xs text-slate-400">Completá los datos y guardá el gasto desde la página.</p></div><button title="Cerrar" onClick={()=>setFixedFormOpen(false)}><X className="w-4 h-4"/></button></div><label className="block mt-5 text-xs text-slate-500">Nombre<input autoFocus value={fixedDraft.nombre} onChange={e=>{setFixedDraft({...fixedDraft,nombre:e.target.value});setFixedFormError('')}} placeholder="Ej: Internet" className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 p-2.5 text-slate-900 dark:text-slate-100"/></label><label className="block mt-3 text-xs text-slate-500">Importe<input type="number" min="0.01" step="any" value={fixedDraft.monto} onChange={e=>{setFixedDraft({...fixedDraft,monto:e.target.value});setFixedFormError('')}} placeholder="0,00" className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 p-2.5 text-slate-900 dark:text-slate-100"/></label>{fixedFormError&&<p className="mt-3 rounded-lg bg-rose-50 dark:bg-rose-950/30 p-2.5 text-xs text-rose-600 dark:text-rose-300">{fixedFormError}</p>}<div className="flex justify-end gap-2 mt-5"><button onClick={()=>setFixedFormOpen(false)} className="rounded-lg border border-slate-200 dark:border-slate-700 px-4 py-2 text-xs font-bold">Cancelar</button><button onClick={()=>{const monto=Number(fixedDraft.monto);if(!fixedDraft.nombre.trim()||!Number.isFinite(monto)||monto<=0){setFixedFormError('Ingresá un nombre y un importe mayor que cero.');return}addFixed({nombre:fixedDraft.nombre,monto})}} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white">Guardar gasto fijo</button></div></div></div>}
 <MobileNavigation language={settings.language||'es'} settingsOpen={showSettings} onOpenSettings={()=>setShowSettings(true)}/>
 {transferMode&&<QuickTransferModal mode={transferMode} accounts={accounts} onClose={()=>setTransferMode(null)} onTransfer={async(data)=>{await addTx(data);setTransferMode(null)}}/>}
 {showInsights&&<InsightsModal settings={settings} categorySpent={categorySpent} summary={{...summary,investment:summary.investmentThisMonth}} transactions={active} month={month} year={year} onClose={()=>setShowInsights(false)} onSave={saveSettings}/>}
 {showAccount&&<AccountModal user={user} language={settings.language||'es'} onClose={()=>setShowAccount(false)} onResetData={resetAllData} onDeleteAccount={removeAccount}/>}
 {showTutorial&&<OnboardingTutorial onFinish={completeTutorial}/>}
 {showCurrencySetup&&<CurrencyPreferenceModal settings={settings} onSave={async monedaBase=>{const monedas=[monedaBase,...settings.monedas.filter(currency=>currency!==monedaBase)];await saveSettings({...settings,monedaBase,monedas,currencySetupCompleted:true});setShowCurrencySetup(false)}}/>}
 {showPrivacy&&<PrivacyPolicyModal language={settings.language||'es'} onClose={()=>setShowPrivacy(false)}/>}
 {showHelp&&<HelpModal language={settings.language||'es'} onClose={()=>setShowHelp(false)}/>}
 {showSettings&&<SettingsPanel settings={settings} accounts={accounts} fixed={fixed} loans={loans} trashedTxs={trashedTxs} correctionValues={{accounts:summary.accounts,cash:summary.cash,patrimony:summary.patrimonio,investment:summary.investment}} onCorrectBalance={correctBalance} onRestoreTx={restoreTx} onPermanentlyDeleteTx={permanentlyDeleteTx} onClose={()=>setShowSettings(false)} onSave={saveSettings} onExport={exportAll} onImport={importBackup} onAddAccount={addAccount} onDeleteAccount={deleteAccount} onAddLoan={addLoan}/>}</div>
}

function CurrencyPreferenceModal({settings,onSave}:{settings:UserSettings;onSave:(currency:string)=>Promise<void>}) {
 const [currency,setCurrency]=useState(settings.monedaBase),[saving,setSaving]=useState(false);
 useEffect(()=>{if(settings.language==='en')return applyLanguage('en',false)},[settings.language]);
 const options=['ARS','USD','EUR','BRL','MXN','CLP','COP','PEN','UYU','GBP','CAD','AUD','JPY','CNY','INR'];
 const labels:Record<string,string>={ARS:'Peso argentino (ARS)',USD:'US Dollar (USD)',EUR:'Euro (EUR)',BRL:'Real brasileño (BRL)',MXN:'Peso mexicano (MXN)',CLP:'Peso chileno (CLP)',COP:'Peso colombiano (COP)',PEN:'Sol peruano (PEN)',UYU:'Peso uruguayo (UYU)',GBP:'Libra esterlina (GBP)',CAD:'Dólar canadiense (CAD)',AUD:'Dólar australiano (AUD)',JPY:'Yen japonés (JPY)',CNY:'Yuan chino (CNY)',INR:'Rupia india (INR)'};
 return <div className="fixed inset-0 z-[110] grid place-items-center bg-slate-950/70 p-4"><section role="dialog" aria-modal="true" aria-label="Moneda preferida" className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><p className="text-[10px] font-bold tracking-wide text-blue-600 dark:text-blue-400">CONFIGURACIÓN INICIAL</p><h2 className="mt-2 text-xl font-bold">Elegí tu moneda preferida</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">La usamos como moneda principal para mostrar tus resúmenes. Podés cambiarla más adelante desde Configuración.</p><label className="mt-5 block text-xs font-bold text-slate-600 dark:text-slate-300">Moneda<select value={currency} onChange={event=>setCurrency(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm dark:border-slate-700 dark:bg-slate-950">{options.map(option=><option key={option} value={option}>{labels[option]}</option>)}</select></label><button type="button" disabled={saving} onClick={async()=>{setSaving(true);await onSave(currency)}} className="mt-5 w-full rounded-xl bg-blue-600 py-3 text-xs font-bold text-white disabled:opacity-60">{saving?'Guardando…':'Continuar'}</button></section></div>
}

function HelpModal({language,onClose}:{language:'es'|'en';onClose:()=>void}) {
 useEffect(()=>{if(language==='en')return applyLanguage('en',false)},[language]);
 return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section role="dialog" aria-modal="true" aria-label={language==='en'?'Help':'Ayuda'} className="w-full max-w-xl rounded-2xl bg-slate-100 p-4 shadow-2xl dark:bg-slate-950"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">{language==='en'?'Help':'Ayuda'}</h2><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-white dark:hover:bg-slate-900"><X className="h-4 w-4"/></button></div><HelpPanel language={language}/></section></div>
}

function AccountModal({user,language,onClose,onResetData,onDeleteAccount}:{user:User;language:'es'|'en';onClose:()=>void;onResetData:()=>Promise<void>;onDeleteAccount:()=>Promise<void>}) {
 const [action,setAction]=useState<'reset'|'delete'|null>(null),[message,setMessage]=useState(''),[working,setWorking]=useState(false);
 useEffect(()=>{if(language==='en')return applyLanguage('en',false)},[language]);
 const execute=async()=>{if(!action)return;setWorking(true);setMessage('');try{if(action==='reset')await onResetData();else await onDeleteAccount();setMessage(action==='reset'?'Tus datos se restablecieron.':'La cuenta fue eliminada.');if(action==='reset')setAction(null)}catch{setMessage(action==='delete'?'No se pudo eliminar la cuenta. Por seguridad, iniciá sesión nuevamente e intentá otra vez.':'No se pudieron restablecer los datos. Intentá nuevamente.')}finally{setWorking(false)}};
 return <div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/60 p-4" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section role="dialog" aria-modal="true" aria-label="Cuenta" className="w-full max-w-md rounded-2xl bg-slate-100 p-4 shadow-2xl dark:bg-slate-950"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold">Cuenta</h2><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-white dark:hover:bg-slate-900"><X className="h-4 w-4"/></button></div><SecurityPanel email={user.email} anonymous={user.isAnonymous} verified={user.emailVerified} onResetPassword={()=>user.email?sendPasswordResetEmail(auth,user.email):Promise.resolve()}/><section className="mt-4 rounded-2xl border border-rose-200 bg-white p-4 dark:border-rose-950/60 dark:bg-slate-900"><h3 className="text-sm font-bold text-rose-700 dark:text-rose-400">Zona de riesgo</h3><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">Estas acciones no se pueden deshacer. Leé las consecuencias antes de confirmar.</p><div className="mt-3 grid gap-2"><button type="button" onClick={()=>setAction('reset')} className="rounded-lg border border-amber-300 px-3 py-2 text-left text-xs font-bold text-amber-700 dark:border-amber-900 dark:text-amber-300">Restablecer datos <span className="block pt-1 text-[10px] font-normal text-slate-500">Borra movimientos, cuentas, préstamos, accesos y preferencias; conserva tu cuenta.</span></button><button type="button" onClick={()=>setAction('delete')} className="rounded-lg border border-rose-300 px-3 py-2 text-left text-xs font-bold text-rose-700 dark:border-rose-900 dark:text-rose-300">Eliminar cuenta <span className="block pt-1 text-[10px] font-normal text-slate-500">Borra todos tus datos y elimina el acceso a GeFi de forma permanente.</span></button></div></section>{action&&<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/25 dark:text-rose-200"><strong>{action==='delete'?'¿Eliminar la cuenta de forma permanente?':'¿Restablecer todos los datos?'}</strong><p className="mt-1">{action==='delete'?'No vas a poder recuperar ni la cuenta ni sus datos.':'Tus movimientos, cuentas, préstamos, accesos y preferencias se borrarán.'}</p><div className="mt-3 flex justify-end gap-2"><button type="button" onClick={()=>setAction(null)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold dark:border-slate-700">Cancelar</button><button type="button" disabled={working} onClick={()=>void execute()} className="rounded-lg bg-rose-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{working?'Procesando…':action==='delete'?'Sí, eliminar cuenta':'Sí, restablecer datos'}</button></div></div>}{message&&<p className="mt-3 rounded-lg bg-slate-200 p-2.5 text-xs text-slate-700 dark:bg-slate-800 dark:text-slate-200">{message}</p>}</section></div>
}

function InsightsModal({settings,categorySpent,summary,transactions,month,year,onClose,onSave}:{settings:UserSettings;categorySpent:Record<string,number>;summary:{income:number;expense:number;investment:number};transactions:Transaction[];month:number;year:number;onClose:()=>void;onSave:(settings:UserSettings)=>Promise<void>}) {
 useEffect(()=>{if(settings.language==='en')return applyLanguage('en',false)},[settings.language]);
 return <div className="fixed inset-0 z-[85] overflow-auto bg-slate-950/60 sm:p-6" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section role="dialog" aria-modal="true" aria-label="Presupuestos y reportes" className="min-h-[100dvh] w-full bg-slate-100 p-4 shadow-2xl dark:bg-slate-950 sm:mx-auto sm:min-h-0 sm:max-w-4xl sm:rounded-2xl sm:p-6"><div className="sticky top-0 z-10 -mx-4 -mt-4 mb-5 flex items-center justify-between border-b border-slate-200 bg-slate-100/95 px-4 py-4 backdrop-blur dark:border-slate-800 dark:bg-slate-950/95 sm:static sm:m-0 sm:mb-5 sm:border-0 sm:bg-transparent sm:p-0"><div><h2 className="font-bold">Presupuestos y reportes</h2><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Análisis del mes seleccionado.</p></div><button type="button" onClick={onClose} aria-label="Cerrar reportes" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 active:scale-95 dark:border-slate-800 dark:bg-slate-900"><X className="h-4 w-4"/></button></div><div className="grid gap-5 md:grid-cols-[.8fr_1.2fr]"><BudgetPanel categories={settings.categorias} budgets={settings.budgets||{}} spent={categorySpent} hidden={settings.hideBalances} onChange={budgets=>void onSave({...settings,budgets})}/><MonthlyReportPanel income={summary.income} expense={summary.expense} investment={summary.investment} categories={categorySpent} transactions={transactions} month={month} year={year} currency={settings.monedaBase} language={settings.language||'es'} hidden={settings.hideBalances}/></div></section></div>
}

function QuickTransferModal({mode,accounts,onClose,onTransfer}:{mode:'toAccount'|'toCash';accounts:Account[];onClose:()=>void;onTransfer:(data:Omit<Transaction,'id'|'createdAt'|'uid'>)=>Promise<void>}) {
 const cashAccounts=accounts.filter(account=>account.tipo==='Efectivo'), regularAccounts=accounts.filter(account=>account.tipo!=='Efectivo');
 const [origin,setOrigin]=useState(mode==='toAccount'?(cashAccounts[0]?.id||''):(regularAccounts[0]?.id||'')),[destination,setDestination]=useState(mode==='toAccount'?(regularAccounts[0]?.id||''):(cashAccounts[0]?.id||'')),[amount,setAmount]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const sourceOptions=mode==='toAccount'?cashAccounts:regularAccounts, destinationOptions=mode==='toAccount'?regularAccounts:cashAccounts;
 const submit=async()=>{const monto=Number(amount);if(!origin||!destination||!Number.isFinite(monto)||monto<=0){setError('Elegí ambos destinos e ingresá un importe mayor que cero.');return}setSaving(true);setError('');try{await onTransfer({fecha:today(),categoria:'Transferencia',monto,moneda:'ARS',cotizacion:1,motivo:mode==='toAccount'?'Transferencia de efectivo a cuenta':'Transferencia de cuenta a efectivo',categoriaDetalle:'Transferencia interna',cuentaOrigen:origin,cuentaDestino:destination})}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo registrar la transferencia.');setSaving(false)}};
 return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/65 p-4"><section className="w-full max-w-sm rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{mode==='toAccount'?'Pasar efectivo a cuenta':'Retirar efectivo de cuenta'}</h2><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Se guardará como transferencia. No modifica gastos, ingresos ni patrimonio.</p></div><button type="button" onClick={onClose} className="rounded-lg p-1 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><X className="h-4 w-4"/></button></div>{(!cashAccounts.length||!regularAccounts.length)?<p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800 dark:bg-amber-950/30 dark:text-amber-300">Necesitás al menos una cuenta de tipo Efectivo y una cuenta bancaria o billetera. Podés agregarlas desde Configuración.</p>:<div className="mt-4 space-y-3"><label className="block text-xs font-medium">Sale de<select value={origin} onChange={event=>setOrigin(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 p-2.5 text-sm dark:border-slate-700 dark:bg-slate-950">{sourceOptions.map(account=><option key={account.id} value={account.id}>{account.nombre}</option>)}</select></label><label className="block text-xs font-medium">Entra a<select value={destination} onChange={event=>setDestination(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 p-2.5 text-sm dark:border-slate-700 dark:bg-slate-950">{destinationOptions.map(account=><option key={account.id} value={account.id}>{account.nombre}</option>)}</select></label><label className="block text-xs font-medium">Importe<input autoFocus type="number" min="0.01" step="any" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0,00" className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 p-2.5 text-sm dark:border-slate-700 dark:bg-slate-950"/></label>{error&&<p className="rounded-lg bg-rose-50 p-2 text-xs text-rose-600 dark:bg-rose-950/30">{error}</p>}<div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold dark:border-slate-700">Cancelar</button><button type="button" disabled={saving} onClick={submit} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{saving?'Registrando…':'Transferir dinero'}</button></div></div>}</section></div>
}

function OnboardingTutorial({onFinish}:{onFinish:()=>void}) {
 const [step,setStep]=useState(0);
 const steps=[
  {icon:'👋',title:'Bienvenido a GeFi',text:'En pocos pasos vas a conocer cómo registrar tu dinero y mantener tu resumen financiero al día.'},
  {icon:'✨',title:'Registro inteligente',text:'Escribí o dictá frases como “hoy gasté 2 mil en helado”. GeFi reconoce fecha, importe, categoría y detalle automáticamente.'},
  {icon:'↔️',title:'Efectivo y cuentas',text:'Tocá las tarjetas Efectivo o En cuentas para mover dinero entre ellas. Se registra como transferencia y no como gasto.'},
  {icon:'📊',title:'Tu resumen',text:'En la parte superior ves patrimonio, cuentas, efectivo, ingresos, gastos e inversiones. Tocá Inversiones para ver su detalle.'},
  {icon:'⚙️',title:'Todo listo',text:'Desde Perfil y configuración podés crear cuentas, categorías, accesos directos y descargar un respaldo. Tus cambios se sincronizan al volver Internet.'},
 ];
 const current=steps[step],last=step===steps.length-1;
 return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/75 p-4"><section role="dialog" aria-modal="true" aria-label="Guía inicial de GeFi" className="w-full max-w-md overflow-hidden rounded-3xl bg-white shadow-2xl dark:bg-slate-900"><div className="bg-gradient-to-r from-slate-950 to-blue-950 px-6 py-5 text-white"><div className="flex items-center justify-between"><span className="text-xs font-bold tracking-wide text-blue-200">GUÍA INICIAL</span><button type="button" onClick={onFinish} className="text-xs text-blue-100 hover:text-white">Omitir</button></div><div className="mt-4 flex gap-1.5">{steps.map((_,index)=><span key={index} className={`h-1.5 flex-1 rounded-full ${index<=step?'bg-blue-300':'bg-white/20'}`}/>)}</div></div><div className="px-6 py-7 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-3xl dark:bg-blue-950/40">{current.icon}</div><h2 className="mt-5 text-xl font-bold">{current.title}</h2><p className="mt-3 min-h-16 text-sm leading-6 text-slate-500 dark:text-slate-400">{current.text}</p></div><div className="flex items-center justify-between border-t border-slate-100 px-6 py-4 dark:border-slate-800"><button type="button" onClick={()=>setStep(value=>Math.max(0,value-1))} disabled={step===0} className="text-xs font-bold text-slate-500 disabled:invisible">Atrás</button><span className="text-xs text-slate-400">{step+1} de {steps.length}</span><button type="button" onClick={last?onFinish:()=>setStep(value=>value+1)} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white">{last?'Empezar':'Siguiente'}</button></div></section></div>
}

function PrivacyPolicyModal({onClose,language}:{onClose:()=>void;language:'es'|'en'}) {
 useEffect(()=>{if(language==='en')return applyLanguage('en',false)},[language]);
 return <div className="fixed inset-0 z-[110] overflow-auto bg-slate-950/70 p-4"><section role="dialog" aria-modal="true" aria-label="Política de privacidad" className="mx-auto my-6 w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Política de Privacidad de GeFi</h2><p className="mt-1 text-xs text-slate-400">Última actualización: 30 de agosto de 2026</p></div><button type="button" onClick={onClose} className="rounded-lg p-1 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><X className="h-5 w-5"/></button></div><div className="mt-6 space-y-5 text-sm leading-6 text-slate-600 dark:text-slate-300"><section><h3 className="font-bold text-slate-800 dark:text-white">1. Datos que guardamos</h3><p>GeFi guarda los movimientos financieros, cuentas, categorías, preferencias, accesos directos y la información básica de tu cuenta necesaria para identificarte y sincronizar tus datos.</p></section><section><h3 className="font-bold text-slate-800 dark:text-white">2. Para qué usamos los datos</h3><p>Usamos esos datos únicamente para mostrar tu resumen financiero, permitirte registrar movimientos, mantener tus preferencias y sincronizar la información entre los dispositivos donde iniciás sesión.</p></section><section><h3 className="font-bold text-slate-800 dark:text-white">3. Almacenamiento y seguridad</h3><p>La información se almacena mediante Firebase. GeFi no vende tus datos ni los comparte con fines publicitarios. Protegé tu cuenta y no compartas tus credenciales de acceso.</p></section><section><h3 className="font-bold text-slate-800 dark:text-white">4. Uso sin conexión</h3><p>Cuando no hay Internet, GeFi puede conservar cambios en el dispositivo. Al volver la conexión, intenta sincronizarlos con tu cuenta.</p></section><section><h3 className="font-bold text-slate-800 dark:text-white">5. Tus controles</h3><p>Podés editar o borrar movimientos desde la app, descargar un respaldo JSON e importar respaldos anteriores. La eliminación de información en tus dispositivos no siempre elimina automáticamente copias que ya estén en un respaldo que hayas descargado.</p></section><section><h3 className="font-bold text-slate-800 dark:text-white">6. Contacto y eliminación de cuenta</h3><p>Para consultas sobre privacidad, eliminación de datos o soporte, escribinos a <a className="font-medium text-blue-600 hover:underline dark:text-blue-400" href="mailto:gefisupport@gmail.com">gefisupport@gmail.com</a>.</p></section><section><h3 className="font-bold text-slate-800 dark:text-white">7. Cambios a esta política</h3><p>Podemos actualizar esta política cuando agreguemos funciones nuevas. La fecha de actualización se mostrará en esta misma sección.</p></section></div><div className="mt-6 flex justify-end"><button type="button" onClick={onClose} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white">Entendido</button></div></section></div>
}

function SettingsPanel({settings,accounts,loans,trashedTxs,correctionValues,onCorrectBalance,onRestoreTx,onPermanentlyDeleteTx,onClose,onSave,onExport,onImport,onAddAccount,onDeleteAccount,onAddLoan}:{settings:UserSettings;accounts:Account[];fixed:FixedExpense[];loans:Loan[];trashedTxs:Transaction[];correctionValues:{accounts:number;cash:number;patrimony:number;investment:number};onCorrectBalance:(kind:'accounts'|'cash'|'patrimony'|'investment',target:number)=>Promise<void>;onRestoreTx:(id:string)=>Promise<void>;onPermanentlyDeleteTx:(id:string)=>Promise<void>;onClose:()=>void;onSave:(x:UserSettings)=>Promise<void>;onExport:()=>void;onImport:(file:File)=>Promise<void>;onAddAccount:(data?:{nombre:string;tipo:Account['tipo'];saldoInicial:number})=>Promise<void>;onDeleteAccount:(id:string)=>Promise<void>;onAddLoan:(data?:{persona:string;monto:number;motivo:string;cuentaId:string})=>Promise<void>}) {
 const [s,setS]=useState(settings), [newCategory,setNewCategory]=useState(''), [saving,setSaving]=useState(false), [accountForm,setAccountForm]=useState(false), [accountDraft,setAccountDraft]=useState({nombre:'',tipo:'Banco' as Account['tipo'],saldoInicial:0}), [linkForm,setLinkForm]=useState(false), [linkDraft,setLinkDraft]=useState({nombre:'',url:''}), [loanForm,setLoanForm]=useState(false), [loanDraft,setLoanDraft]=useState({persona:'',monto:0,motivo:'',cuentaId:''}), [correctionKind,setCorrectionKind]=useState<'accounts'|'cash'|'patrimony'|'investment'>('accounts'), [correctionTarget,setCorrectionTarget]=useState(String(correctionValues.accounts)), [deleteAccountTarget,setDeleteAccountTarget]=useState<Account|null>(null), [deleteTrashTarget,setDeleteTrashTarget]=useState<Transaction|null>(null), [importFile,setImportFile]=useState<File|null>(null), [formError,setFormError]=useState('');
 useEffect(()=>{if(s.language==='en')return applyLanguage('en',false);if(settings.language==='en')return applyLanguage('es',false)},[s.language,settings.language]);
 const inputClass='block mt-1 p-2 border border-slate-200 dark:border-slate-700 rounded-lg w-full bg-white dark:bg-slate-950 text-slate-800 dark:text-slate-100';
 const scrollToConfig=(title:string)=>{const heading=[...document.querySelectorAll('h3,p,label')].find(element=>element.textContent?.trim()===title|| (title==='Preferencias'&&element.textContent?.includes('Moneda base')));heading?.scrollIntoView({behavior:'smooth',block:'start'})};
 const addCategory=()=>{const value=newCategory.trim();if(!value||s.categorias.some(x=>x.toLowerCase()===value.toLowerCase()))return;setS({...s,categorias:[...s.categorias,value]});setNewCategory('')};
 const addLink=()=>{if(!/^https?:\/\//.test(linkDraft.url.trim())){setFormError('Ingresá una URL que comience con http:// o https://. El nombre es opcional.');return}setS({...s,quickLinks:[...s.quickLinks,{id:crypto.randomUUID(),nombre:linkDraft.nombre.trim(),url:linkDraft.url.trim()}]});setLinkDraft({nombre:'',url:''});setLinkForm(false);setFormError('')};
 const createAccount=async()=>{if(!accountDraft.nombre.trim()||accountDraft.saldoInicial<0){setFormError('Ingresá un nombre y un saldo inicial válido.');return}setSaving(true);await onAddAccount({...accountDraft,nombre:accountDraft.nombre.trim()});setSaving(false);setAccountDraft({nombre:'',tipo:'Banco',saldoInicial:0});setAccountForm(false);setFormError('')};
 const createLoan=async()=>{if(!loanDraft.persona.trim()||loanDraft.monto<=0){setFormError('Ingresá una persona y un importe mayor que cero.');return}setSaving(true);await onAddLoan({...loanDraft,persona:loanDraft.persona.trim()});setSaving(false);setLoanDraft({persona:'',monto:0,motivo:'',cuentaId:''});setLoanForm(false);setFormError('')};
 const applyCorrection=async()=>{const target=Number(correctionTarget);if(!Number.isFinite(target)){setFormError('Ingresá un importe válido.');return}const current=correctionValues[correctionKind];if(Math.abs(target-current)<0.01){setFormError('El nuevo importe es igual al saldo actual.');return}setSaving(true);await onCorrectBalance(correctionKind,target);setSaving(false);setFormError('');setCorrectionTarget(String(target))};
 const save=async()=>{setSaving(true);await onSave(s);setSaving(false);onClose()};
 return <div className="fixed inset-0 z-[60] overflow-auto bg-slate-950/60 p-0 sm:p-4"><section className="mx-auto min-h-dvh w-full bg-white p-4 text-slate-800 shadow-2xl dark:bg-slate-900 dark:text-slate-100 sm:my-8 sm:min-h-0 sm:max-w-3xl sm:rounded-2xl sm:p-6">
  <div className="flex justify-between items-center"><h2 className="font-bold text-lg">Configuración</h2><button onClick={onClose} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800" title="Cerrar sin guardar"><X className="w-4 h-4"/></button></div>
  <nav aria-label="Secciones de configuración" className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-2 dark:bg-slate-950 sm:grid-cols-4">{['Preferencias','Categorías de gasto','Cuentas y efectivo','Préstamos','Accesos directos','Papelera de movimientos','Respaldo de datos','Accesibilidad'].map(section=><button key={section} type="button" onClick={()=>scrollToConfig(section)} className="rounded-lg px-2 py-2 text-left text-[10px] font-bold text-slate-600 hover:bg-white hover:text-blue-600 dark:text-slate-300 dark:hover:bg-slate-900 dark:hover:text-blue-300">{section}</button>)}</nav>
  <div className="grid sm:grid-cols-2 gap-5 mt-5"><label className="text-xs">Moneda base<select value={s.monedaBase} onChange={e=>setS({...s,monedaBase:e.target.value})} className={inputClass}>{s.monedas.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="text-xs">Idioma<select value={s.language||'es'} onChange={e=>setS({...s,language:e.target.value as 'es'|'en'})} className={inputClass}><option value="es">Español</option><option value="en">English</option></select></label></div>
  <label className="mt-5 flex items-center justify-between rounded-xl border border-slate-200 dark:border-slate-800 p-3 text-xs"><span><strong className="block">Sección de ahorros</strong><small className="text-slate-400">Mostrar los ahorros en la pantalla principal.</small></span><input type="checkbox" checked={s.showSavings!==false} onChange={e=>setS({...s,showSavings:e.target.checked})} className="w-4 h-4 accent-blue-600"/></label>
  <InvestmentPreferences settings={s} onChange={setS}/>
  <section className="mt-6 rounded-xl border border-slate-200 p-4 dark:border-slate-800"><h3 className="text-sm font-bold">Avisos por correo</h3><p className="mt-1 text-[10px] text-slate-400">Elegí qué resúmenes querés recibir en el correo de tu cuenta.</p><label className="mt-3 flex items-center justify-between gap-3 text-xs"><span><strong className="block">Resumen mensual</strong><small className="text-slate-400">Balance del mes terminado, comienzo del nuevo mes y un tip financiero.</small></span><input type="checkbox" checked={s.monthlyEmailSummary!==false} onChange={event=>setS({...s,monthlyEmailSummary:event.target.checked})} className="h-4 w-4 accent-blue-600"/></label><label className="mt-3 flex items-center justify-between gap-3 border-t border-slate-100 pt-3 text-xs dark:border-slate-800"><span><strong className="block">Recordatorios de pagos</strong><small className="text-slate-400">Avisos por correo antes de vencer, el mismo día y al quedar vencido.</small></span><input type="checkbox" checked={s.paymentEmailReminders!==false} onChange={event=>setS({...s,paymentEmailReminders:event.target.checked})} className="h-4 w-4 accent-blue-600"/></label></section>
  <div className="mt-6"><h3 className="font-bold text-sm mb-2">Categorías de gasto</h3><div className="flex gap-2"><input value={newCategory} onChange={e=>setNewCategory(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addCategory()} placeholder="Nueva categoría" className={`${inputClass} mt-0`}/><button onClick={addCategory} className="bg-blue-600 text-white rounded-lg px-3 text-xs font-bold">Agregar</button></div><div className="flex flex-wrap gap-2 mt-3">{s.categorias.map(category=><span key={category} className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 dark:bg-slate-800 px-3 py-1.5 text-xs">{category}<button onClick={()=>setS({...s,categorias:s.categorias.filter(x=>x!==category)})} title={`Eliminar ${category}`} className="text-slate-400 hover:text-rose-600"><X className="w-3 h-3"/></button></span>)}</div></div>
  <div className="mt-6 rounded-xl border border-blue-200 dark:border-blue-900/60 bg-blue-50/60 dark:bg-blue-950/20 p-4"><div><h3 className="font-bold text-sm">Corrección de cuenta</h3><p className="mt-1 text-[10px] text-slate-500 dark:text-slate-400">Ajustá un total de la pantalla principal. La diferencia quedará registrada como un movimiento.</p></div><div className="grid sm:grid-cols-2 gap-3 mt-3"><label className="text-xs">Saldo a corregir<select value={correctionKind} onChange={e=>{const kind=e.target.value as 'accounts'|'cash'|'patrimony'|'investment';setCorrectionKind(kind);setCorrectionTarget(String(correctionValues[kind]));setFormError('')}} className={inputClass}><option value="accounts">Dinero en cuenta</option><option value="cash">Efectivo</option><option value="patrimony">Patrimonio total</option><option value="investment">Saldo total de inversiones</option></select></label><label className="text-xs">Nuevo importe<input type="number" step="any" value={correctionTarget} onChange={e=>{setCorrectionTarget(e.target.value);setFormError('')}} className={inputClass}/></label></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div className="text-xs"><span className="text-slate-500 dark:text-slate-400">Actual: </span><strong>{new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(correctionValues[correctionKind])}</strong>{Number.isFinite(Number(correctionTarget))&&Math.abs(Number(correctionTarget)-correctionValues[correctionKind])>=0.01&&<span className={`ml-2 font-bold ${Number(correctionTarget)>correctionValues[correctionKind]?'text-emerald-600':'text-rose-600'}`}>{Number(correctionTarget)>correctionValues[correctionKind]?`+ ${new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(Number(correctionTarget)-correctionValues[correctionKind])} como ${correctionKind==='investment'?'inversión':'ingreso'}`:`- ${new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(correctionValues[correctionKind]-Number(correctionTarget))} como ${correctionKind==='investment'?'desinversión':'gasto'}`}</span>}</div><button disabled={saving} onClick={applyCorrection} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-60">{saving?'Aplicando…':'Aplicar corrección'}</button></div></div>
  <div className="mt-6"><div className="flex justify-between"><h3 className="font-bold text-sm">Cuentas y efectivo</h3><button onClick={()=>{setFormError('');setAccountForm(true)}} className="text-xs text-blue-600 dark:text-blue-400">Agregar</button></div>{accountForm&&<div className="mt-3 grid sm:grid-cols-3 gap-2 rounded-xl bg-slate-50 dark:bg-slate-950 p-3"><input autoFocus value={accountDraft.nombre} onChange={e=>setAccountDraft({...accountDraft,nombre:e.target.value})} placeholder="Nombre de la cuenta" className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"/><select value={accountDraft.tipo} onChange={e=>setAccountDraft({...accountDraft,tipo:e.target.value as Account['tipo']})} className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"><option>Banco</option><option>Billetera</option><option>Efectivo</option></select><input type="number" min="0" value={accountDraft.saldoInicial} onChange={e=>setAccountDraft({...accountDraft,saldoInicial:Number(e.target.value)})} placeholder="Saldo inicial" className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"/><div className="sm:col-span-3 flex justify-end gap-2"><button onClick={()=>setAccountForm(false)} className="border border-slate-200 dark:border-slate-700 rounded-lg px-3 py-1.5 text-xs">Cancelar</button><button onClick={createAccount} className="bg-blue-600 text-white rounded-lg px-3 py-1.5 text-xs font-bold">Guardar cuenta</button></div></div>}{accounts.length===0?<p className="text-xs text-slate-400 py-2">No hay cuentas configuradas.</p>:accounts.map(a=><div key={a.id} className="flex justify-between items-center text-xs py-2 border-b border-slate-200 dark:border-slate-800"><span>{a.nombre} · {a.tipo} · {a.moneda}</span><button onClick={()=>{setFormError('');setDeleteAccountTarget(a)}} className="inline-flex items-center gap-1 text-rose-600"><Trash2 className="w-3 h-3"/> Eliminar</button></div>)}</div>
  <div className="mt-6"><div className="flex justify-between"><h3 className="font-bold text-sm">Préstamos</h3><button onClick={()=>{setFormError('');setLoanForm(true)}} className="text-xs text-blue-600 dark:text-blue-400">Agregar</button></div>{loanForm&&<div className="mt-3 grid sm:grid-cols-2 gap-2 rounded-xl bg-slate-50 dark:bg-slate-950 p-3"><input autoFocus value={loanDraft.persona} onChange={e=>setLoanDraft({...loanDraft,persona:e.target.value})} placeholder="Persona" className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"/><input type="number" min="0.01" value={loanDraft.monto} onChange={e=>setLoanDraft({...loanDraft,monto:Number(e.target.value)})} placeholder="Importe" className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"/><input value={loanDraft.motivo} onChange={e=>setLoanDraft({...loanDraft,motivo:e.target.value})} placeholder="Motivo (opcional)" className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"/><select value={loanDraft.cuentaId} onChange={e=>setLoanDraft({...loanDraft,cuentaId:e.target.value})} className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"><option value="">Sin cuenta</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.nombre}</option>)}</select><div className="sm:col-span-2 flex justify-end gap-2"><button onClick={()=>setLoanForm(false)} className="border border-slate-200 dark:border-slate-700 rounded-lg px-3 py-1.5 text-xs">Cancelar</button><button onClick={createLoan} className="bg-blue-600 text-white rounded-lg px-3 py-1.5 text-xs font-bold">Guardar préstamo</button></div></div>}{loans.map(l=><p className="text-xs py-1" key={l.id}>{l.persona}: {l.monto} {l.moneda} · {l.estado}</p>)}</div>
  <div className="mt-6"><div className="flex justify-between"><div><h3 className="font-bold text-sm">Accesos directos</h3><p className="text-[10px] text-slate-400">La URL es obligatoria; el nombre es opcional.</p></div><button onClick={()=>{setFormError('');setLinkForm(true)}} className="text-xs text-blue-600 dark:text-blue-400">Agregar acceso</button></div>{linkForm&&<div className="mt-3 grid sm:grid-cols-2 gap-2 rounded-xl bg-slate-50 dark:bg-slate-950 p-3"><input value={linkDraft.nombre} onChange={e=>setLinkDraft({...linkDraft,nombre:e.target.value})} placeholder="Nombre (opcional)" className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"/><input autoFocus value={linkDraft.url} onChange={e=>setLinkDraft({...linkDraft,url:e.target.value})} placeholder="https://ejemplo.com (obligatorio)" className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-xs"/><div className="sm:col-span-2 flex justify-end gap-2"><button onClick={()=>setLinkForm(false)} className="border border-slate-200 dark:border-slate-700 rounded-lg px-3 py-1.5 text-xs">Cancelar</button><button onClick={addLink} className="bg-blue-600 text-white rounded-lg px-3 py-1.5 text-xs font-bold">Agregar acceso</button></div></div>}{s.quickLinks.map(q=><div className="flex justify-between text-xs py-2 border-b border-slate-200 dark:border-slate-800" key={q.id}><a href={q.url} target="_blank" rel="noreferrer" title={quickLinkLabel(q.url,q.nombre)} className="text-blue-600 dark:text-blue-400 flex items-center gap-2"><QuickLinkIcon url={q.url} name={q.nombre}/>{quickLinkLabel(q.url,q.nombre)}<ExternalLink className="w-3 h-3"/></a><button onClick={()=>setS({...s,quickLinks:s.quickLinks.filter(x=>x.id!==q.id)})} className="text-rose-600">Eliminar</button></div>)}</div>
  <div className="mt-6"><div className="flex items-center justify-between"><div><h3 className="font-bold text-sm">Papelera de movimientos</h3><p className="text-[10px] text-slate-400">Los movimientos se eliminan definitivamente después de 30 días.</p></div><span className="rounded-full bg-slate-100 dark:bg-slate-800 px-2.5 py-1 text-[10px] font-bold">{trashedTxs.length}</span></div>{trashedTxs.length===0?<p className="py-3 text-xs text-slate-400">La papelera está vacía.</p>:<div className="mt-2 max-h-52 overflow-auto">{trashedTxs.map(t=>{const days=Math.max(1,30-Math.floor((Date.now()-(t.deletedAt||Date.now()))/(24*60*60*1000)));return <div key={t.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 dark:border-slate-800 py-2 text-xs"><div><strong>{t.motivo}</strong><span className="ml-2 text-slate-400">{t.monto} {t.moneda||'ARS'} · {days} días restantes</span></div><div className="flex gap-2"><button onClick={()=>onRestoreTx(t.id)} className="font-bold text-emerald-600">Restaurar</button><button onClick={()=>setDeleteTrashTarget(t)} className="text-rose-600">Eliminar definitivamente</button></div></div>})}</div>}</div>
  <div className="mt-6"><AccessibilityPanel value={s.fontScale||'normal'} onChange={fontScale=>setS({...s,fontScale})}/></div>
  {formError&&<p className="mt-3 rounded-lg bg-rose-50 dark:bg-rose-950/30 p-2.5 text-xs text-rose-600 dark:text-rose-300">{formError}</p>}
  <div className="mt-7 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><p className="text-xs font-bold">Respaldo de datos</p><p className="mt-1 text-[10px] text-slate-400">Descargá una copia de tus datos o recuperá un respaldo de GeFi. La importación combina el archivo con tus datos actuales.</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={onExport} className="border border-slate-200 dark:border-slate-700 rounded-lg px-3 py-2 text-xs flex gap-1 items-center"><Download className="w-3 h-3"/> Descargar JSON</button><label className="cursor-pointer rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700 dark:border-blue-900/60 dark:bg-blue-950/30 dark:text-blue-300">Elegir respaldo<input type="file" accept="application/json,.json" className="hidden" onChange={event=>{setImportFile(event.target.files?.[0]||null);setFormError('')}}/></label>{importFile&&<button disabled={saving} onClick={async()=>{setSaving(true);try{await onImport(importFile);setImportFile(null);setFormError('Respaldo importado correctamente.')}catch(error){setFormError(error instanceof Error?error.message:'No se pudo importar el respaldo.')}finally{setSaving(false)}}} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-60">Importar {importFile.name}</button>}</div></div>
  <div className="mt-4 flex flex-wrap gap-2"><button disabled={saving} onClick={save} className="bg-blue-600 disabled:opacity-60 text-white rounded-lg px-4 py-2 text-xs font-bold">{saving?'Guardando…':'Guardar configuración'}</button><button onClick={onClose} className="border border-slate-200 dark:border-slate-700 rounded-lg px-4 py-2 text-xs">Cancelar</button></div>
  {deleteAccountTarget&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/65 p-4"><div className="w-full max-w-sm rounded-2xl bg-white dark:bg-slate-900 p-6 shadow-2xl"><h3 className="font-bold">Eliminar cuenta</h3><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">¿Querés eliminar <strong className="text-slate-800 dark:text-slate-100">{deleteAccountTarget.nombre}</strong>? Los movimientos existentes conservarán sus importes.</p><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setDeleteAccountTarget(null)} className="border border-slate-200 dark:border-slate-700 rounded-lg px-4 py-2 text-xs font-bold">Cancelar</button><button onClick={async()=>{await onDeleteAccount(deleteAccountTarget.id);setDeleteAccountTarget(null)}} className="bg-rose-600 text-white rounded-lg px-4 py-2 text-xs font-bold">Sí, eliminar</button></div></div></div>}
  {deleteTrashTarget&&<div className="fixed inset-0 z-[95] grid place-items-center bg-slate-950/65 p-4"><div className="w-full max-w-sm rounded-2xl bg-white dark:bg-slate-900 p-6 shadow-2xl"><h3 className="font-bold">Eliminar definitivamente</h3><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">¿Querés eliminar para siempre <strong className="text-slate-800 dark:text-slate-100">{deleteTrashTarget.motivo}</strong>? Después no se podrá recuperar.</p><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setDeleteTrashTarget(null)} className="border border-slate-200 dark:border-slate-700 rounded-lg px-4 py-2 text-xs font-bold">Cancelar</button><button onClick={async()=>{await onPermanentlyDeleteTx(deleteTrashTarget.id);setDeleteTrashTarget(null)}} className="bg-rose-600 text-white rounded-lg px-4 py-2 text-xs font-bold">Eliminar para siempre</button></div></div></div>}
 </section></div>
}
