type Language = 'es' | 'en';

const phrases: Record<string, string> = {
  'Gestor Financiero': 'Financial Manager', 'Mi Gestor Financiero': 'My Financial Manager', 'Nuevo Movimiento': 'New transaction', 'Registro inteligente': 'Smart entry',
  'Interpretar y registrar': 'Interpret and save', 'AGREGAR REGISTRO': 'ADD TRANSACTION', 'Hablar': 'Speak', 'Escuchando…': 'Listening…', 'Registrando…': 'Saving…',
  'Patrimonio total': 'Total net worth', 'En cuentas': 'In accounts', 'Efectivo': 'Cash', 'Ingresos': 'Income', 'Gastos': 'Expenses', 'Mayor gasto': 'Highest expense', 'Inversiones': 'Investments',
  'Tocá para transferir': 'Tap to transfer', 'Tocá para ver detalle': 'Tap for details', 'Detalle de inversiones': 'Investment details',
  'Perfil y configuración': 'Profile and settings', 'Guardar configuración': 'Save settings', 'Cancelar': 'Cancel', 'Guardar cambios': 'Save changes',
  'Moneda base': 'Base currency', 'Monedas configuradas': 'Configured currencies', 'Categorías de gasto': 'Expense categories', 'Nueva categoría': 'New category', 'Agregar': 'Add',
  'Corrección de cuenta': 'Balance correction', 'Saldo a corregir': 'Balance to correct', 'Nuevo importe': 'New amount', 'Aplicar corrección': 'Apply correction',
  'Cuentas y efectivo': 'Accounts and cash', 'Agregar cuenta': 'Add account', 'Nombre de la cuenta': 'Account name', 'Guardar cuenta': 'Save account', 'Eliminar cuenta': 'Delete account',
  'Préstamos': 'Loans', 'Prestar dinero': 'Lend money', 'Guardar préstamo': 'Save loan', 'Persona': 'Person', 'Importe': 'Amount', 'Motivo (opcional)': 'Reason (optional)',
  'Préstamos realizados': 'Loans made', 'Total que te deben': 'Total owed to you', 'Total pendiente:': 'Total pending:', 'Marcar pagado': 'Mark as paid',
  'Accesos directos': 'Shortcuts', 'Agregar acceso': 'Add shortcut', 'Nombre (opcional)': 'Name (optional)', 'Eliminar': 'Delete', 'Modificar acceso': 'Edit shortcut',
  'Papelera de movimientos': 'Transaction bin', 'Restaurar': 'Restore', 'Eliminar definitivamente': 'Delete permanently', 'Eliminar para siempre': 'Delete forever',
  'Descargar JSON': 'Download JSON', 'Respaldo de datos': 'Data backup', 'Elegir respaldo': 'Choose backup', 'Importar': 'Import',
  'Descargá una copia de tus datos o recuperá un respaldo de GeFi. La importación combina el archivo con tus datos actuales.': 'Download a copy of your data or restore a GeFi backup. Importing combines the file with your current data.', 'Respaldo importado correctamente.': 'Backup imported successfully.',
  'Política de privacidad': 'Privacy policy', 'Términos de uso': 'Terms of use', 'Soporte': 'Support', 'Ayuda': 'Help', '¿Necesitás ayuda?': 'Need help?',
  'Bienvenido a GeFi': 'Welcome to GeFi', 'GUÍA INICIAL': 'GETTING STARTED', 'Omitir': 'Skip', 'Siguiente': 'Next', 'Atrás': 'Back', 'Empezar': 'Get started', 'Entendido': 'Got it',
  'Fecha': 'Date', 'Categoría': 'Category', 'Monto': 'Amount', 'Cuenta origen': 'Source account', 'Cuenta destino': 'Destination account', 'Sale de': 'From', 'Entra a': 'To',
  'Ingreso': 'Income', 'Gasto': 'Expense', 'Inversión': 'Investment', 'Ahorro': 'Savings', 'Transferencia entre cuenta y efectivo': 'Transfer between account and cash', 'Préstamo': 'Loan',
  'Motivo / Detalle': 'Reason / Details', 'Ver más': 'See more', 'Ver menos': 'See less', 'Sin cuenta': 'No account', 'Seleccionar': 'Select',
  'Pasar efectivo a cuenta': 'Deposit cash to account', 'Retirar efectivo de cuenta': 'Withdraw cash from account', 'Transferir dinero': 'Transfer money',
  'Idioma': 'Language', 'Español': 'Spanish', 'Idioma / Language': 'Language / Idioma',
  'Preferencias generales': 'General preferences', 'Organización': 'Organization', 'Datos': 'Data', 'Secciones de configuración': 'Settings sections', 'Cerrar sin guardar': 'Close without saving',
  'Presupuestos del mes': 'Monthly budgets', 'Definí un límite por categoría y seguí cuánto llevás gastado.': 'Set a limit for each category and track how much you have spent.', 'Todavía no configuraste presupuestos.': 'You have not set up any budgets yet.', 'Configurar límites': 'Set limits', 'Definir': 'Set',
  'Ver presupuestos y reportes': 'View budgets and reports', 'Presupuestos y reportes': 'Budgets and reports', 'Análisis del mes seleccionado.': 'Analysis for the selected month.',
  'Metas de ahorro': 'Savings goals', 'Tus movimientos de ahorro actualizan el progreso.': 'Your savings transactions update the progress.', 'Fondo de emergencia': 'Emergency fund', 'Objetivo': 'Goal', 'Eliminar meta': 'Delete goal', 'Creá una meta para visualizar el avance de tus ahorros.': 'Create a goal to track your savings progress.',
  'Cambios sincronizados': 'Changes synced',
  'Plataformas de inversión': 'Investment platforms', 'Elegí las aplicaciones que usás. Se mostrarán al registrar y consultar inversiones.': 'Choose the apps you use. They will appear when recording and reviewing investments.', 'Plataforma de inversión': 'Investment platform', 'Sin plataformas configuradas.': 'No platforms configured.', 'Agregá al menos una plataforma para clasificar tus próximas inversiones.': 'Add at least one platform to classify your next investments.',
  'Calendario de pagos': 'Payment calendar', 'Avisos próximos, del día y vencidos.': 'Upcoming, due today, and overdue alerts.', 'Activar notificaciones': 'Enable notifications', 'Guardar recordatorio': 'Save reminder', 'Avisar con anticipación': 'Notify me in advance', 'Monto opcional': 'Optional amount', 'Todavía no agregaste pagos al calendario.': 'You have not added any payments to the calendar yet.', 'Marcar pendiente': 'Mark as pending', 'Eliminar recordatorio': 'Delete reminder', 'Vence hoy': 'Due today', 'Pagado': 'Paid',
  'Avisos por correo': 'Email notifications', 'Elegí qué resúmenes querés recibir en el correo de tu cuenta.': 'Choose which summaries you want to receive at your account email.', 'Resumen mensual': 'Monthly summary', 'Balance del mes terminado, comienzo del nuevo mes y un tip financiero.': 'Previous month balance, new month opening, and a financial tip.', 'Recordatorios de pagos': 'Payment reminders', 'Avisos por correo antes de vencer, el mismo día y al quedar vencido.': 'Email alerts before, on, and after the due date.',
  'Reporte del mes': 'Monthly report', 'Resumen de tus movimientos del período seleccionado.': 'Summary of your transactions for the selected period.', 'Gastos por categoría': 'Expenses by category', 'Todavía no hay gastos para mostrar este mes.': 'There are no expenses to show this month.', 'Flujo acumulado': 'Cumulative cash flow', 'Ingresos menos gastos e inversiones': 'Income minus expenses and investments', 'Todavía no hay movimientos para mostrar este mes.': 'There are no transactions to show this month.', 'Cerrar reportes': 'Close reports',
  'Ayuda rápida': 'Quick help', 'Respuestas a las dudas más frecuentes.': 'Answers to the most common questions.', '¿Cómo se guardan mis cambios?': 'How are my changes saved?', 'GeFi guarda los cambios en tu dispositivo y los sincroniza automáticamente con tu cuenta cuando hay Internet.': 'GeFi saves changes on your device and automatically syncs them with your account when there is an Internet connection.', '¿Puedo usar GeFi sin Internet?': 'Can I use GeFi without Internet?', 'Sí. Podés registrar movimientos sin conexión; se enviarán a tu cuenta cuando vuelva Internet.': 'Yes. You can record transactions offline; they will be sent to your account when Internet returns.', '¿Cómo hago un respaldo?': 'How do I create a backup?', 'Abrí Configuración y usá “Descargar JSON” para guardar una copia de tus datos.': 'Open Settings and use “Download JSON” to save a copy of your data.', '¿Cómo cambio el idioma?': 'How do I change the language?', 'Tocá el ícono de idioma junto a Configuración y elegí Español o English.': 'Tap the language icon next to Settings and choose Spanish or English.', 'Contactar soporte': 'Contact support',
  'Seguridad de la cuenta': 'Account security', 'Tus datos se guardan separados por cuenta y solo son accesibles después de iniciar sesión.': 'Your data is stored separately for each account and is only accessible after signing in.', 'Modo invitado': 'Guest mode', 'Para conservar y recuperar tus datos en otros dispositivos, usá una cuenta con correo.': 'To keep and recover your data on other devices, use an account with an email address.', 'Correo verificado.': 'Verified email.', 'La seguridad de tu cuenta depende de mantener privado tu acceso.': 'Your account security depends on keeping your access private.', 'Cambiar contraseña': 'Change password',
  'Te enviamos un correo para cambiar la contraseña. Revisá también el correo no deseado.': 'We sent you an email to change your password. Please also check your spam folder.', 'No se pudo enviar el correo. Intentá nuevamente más tarde.': 'The email could not be sent. Please try again later.',
  'Accesibilidad': 'Accessibility', 'Elegí el tamaño de texto más cómodo para vos.': 'Choose the text size that is most comfortable for you.', 'Normal': 'Normal', 'Grande': 'Large', 'Muy grande': 'Extra large',
  'GeFi necesita recargarse': 'GeFi needs to reload', 'Tus datos no se borraron. Actualizá la página para volver a abrir la aplicación.': 'Your data was not deleted. Refresh the page to open the app again.', 'Recargar GeFi': 'Reload GeFi',
  'Configuración': 'Settings', 'Preferencias': 'Preferences', 'Zona de riesgo': 'Danger zone', 'Estas acciones no se pueden deshacer. Leé las consecuencias antes de confirmar.': 'These actions cannot be undone. Read the consequences before confirming.', 'Restablecer datos': 'Reset data', 'Borra movimientos, cuentas, préstamos, accesos y preferencias; conserva tu cuenta.': 'Deletes transactions, accounts, loans, shortcuts, and preferences; keeps your account.', 'Borra todos tus datos y elimina el acceso a GeFi de forma permanente.': 'Deletes all your data and permanently removes access to GeFi.', '¿Eliminar la cuenta de forma permanente?': 'Permanently delete the account?', '¿Restablecer todos los datos?': 'Reset all data?', 'No vas a poder recuperar ni la cuenta ni sus datos.': 'You will not be able to recover either the account or its data.', 'Tus movimientos, cuentas, préstamos, accesos y preferencias se borrarán.': 'Your transactions, accounts, loans, shortcuts, and preferences will be deleted.', 'Sí, eliminar cuenta': 'Yes, delete account', 'Sí, restablecer datos': 'Yes, reset data', 'Procesando…': 'Processing…',
  'CONFIGURACIÓN INICIAL': 'INITIAL SETUP', 'Elegí tu moneda preferida': 'Choose your preferred currency', 'La usamos como moneda principal para mostrar tus resúmenes. Podés cambiarla más adelante desde Configuración.': 'We use it as your main currency to show your summaries. You can change it later in Settings.', 'Peso argentino (ARS)': 'Argentine peso (ARS)', 'Real brasileño (BRL)': 'Brazilian real (BRL)', 'Peso mexicano (MXN)': 'Mexican peso (MXN)', 'Peso chileno (CLP)': 'Chilean peso (CLP)', 'Peso colombiano (COP)': 'Colombian peso (COP)', 'Sol peruano (PEN)': 'Peruvian sol (PEN)', 'Peso uruguayo (UYU)': 'Uruguayan peso (UYU)', 'Libra esterlina (GBP)': 'Pound sterling (GBP)', 'Dólar canadiense (CAD)': 'Canadian dollar (CAD)', 'Dólar australiano (AUD)': 'Australian dollar (AUD)', 'Yen japonés (JPY)': 'Japanese yen (JPY)', 'Yuan chino (CNY)': 'Chinese yuan (CNY)', 'Rupia india (INR)': 'Indian rupee (INR)', 'Continuar': 'Continue',
  'Política de Privacidad de GeFi': 'GeFi Privacy Policy', 'Última actualización: 30 de agosto de 2026': 'Last updated: August 30, 2026', '1. Datos que guardamos': '1. Data we store', 'GeFi guarda los movimientos financieros, cuentas, categorías, preferencias, accesos directos y la información básica de tu cuenta necesaria para identificarte y sincronizar tus datos.': 'GeFi stores your financial transactions, accounts, categories, preferences, shortcuts, and the basic account information needed to identify you and sync your data.', '2. Para qué usamos los datos': '2. How we use your data', 'Usamos esos datos únicamente para mostrar tu resumen financiero, permitirte registrar movimientos, mantener tus preferencias y sincronizar la información entre los dispositivos donde iniciás sesión.': 'We use this data only to show your financial summary, let you record transactions, keep your preferences, and sync information across the devices where you sign in.', '3. Almacenamiento y seguridad': '3. Storage and security', 'La información se almacena mediante Firebase. GeFi no vende tus datos ni los comparte con fines publicitarios. Protegé tu cuenta y no compartas tus credenciales de acceso.': 'Your information is stored using Firebase. GeFi does not sell your data or share it for advertising. Protect your account and do not share your login credentials.', '4. Uso sin conexión': '4. Offline use', 'Cuando no hay Internet, GeFi puede conservar cambios en el dispositivo. Al volver la conexión, intenta sincronizarlos con tu cuenta.': 'When there is no Internet connection, GeFi can keep changes on your device. When the connection returns, it tries to sync them with your account.', '5. Tus controles': '5. Your controls', 'Podés editar o borrar movimientos desde la app, descargar un respaldo JSON e importar respaldos anteriores. La eliminación de información en tus dispositivos no siempre elimina automáticamente copias que ya estén en un respaldo que hayas descargado.': 'You can edit or delete transactions in the app, download a JSON backup, and import previous backups. Deleting information on your devices does not always automatically remove copies already included in a backup you downloaded.', '6. Contacto y eliminación de cuenta': '6. Contact and account deletion', 'Para consultas sobre privacidad, eliminación de datos o soporte, escribinos a': 'For privacy, data deletion, or support questions, write to', '7. Cambios a esta política': '7. Changes to this policy', 'Podemos actualizar esta política cuando agreguemos funciones nuevas. La fecha de actualización se mostrará en esta misma sección.': 'We may update this policy when we add new features. The update date will appear in this same section.',
  'Control personal de ingresos, gastos y efectivo': 'Personal income, expenses and cash control', 'Mes Anterior': 'Previous month', 'Mes Siguiente': 'Next month', 'Usuario': 'User', 'Modo Invitado': 'Guest mode', 'Mostrar montos': 'Show balances', 'Ocultar montos': 'Hide balances', 'Cambiar a Modo Claro': 'Switch to light mode', 'Cambiar a Modo Oscuro': 'Switch to dark mode', 'Cerrar Sesión': 'Sign out',
  'Enero': 'January', 'Febrero': 'February', 'Marzo': 'March', 'Abril': 'April', 'Mayo': 'May', 'Junio': 'June', 'Julio': 'July', 'Agosto': 'August', 'Septiembre': 'September', 'Octubre': 'October', 'Noviembre': 'November', 'Diciembre': 'December',
  'Administra tus finanzas personales mes a mes de forma segura': 'Manage your personal finances securely, month by month', 'Selecciona un método de acceso': 'Choose a sign-in method', 'Iniciar con Google': 'Sign in with Google', 'Correo electrónico': 'Email address', 'Contraseña (mín. 6 caracteres)': 'Password (min. 6 characters)', 'INGRESAR CON CONTRASEÑA': 'SIGN IN WITH PASSWORD', 'CREAR CUENTA': 'CREATE ACCOUNT', 'Crear cuenta con correo y contraseña': 'Create account with email and password', 'Ya tengo una cuenta': 'I already have an account', 'O TAMBIÉN': 'OR', 'Entrar como Invitado': 'Continue as guest', 'Tus datos se sincronizan de forma segura entre tus dispositivos.': 'Your data syncs securely across your devices.', 'Privacidad': 'Privacy',
  'Describí el movimiento con tus palabras.': 'Describe the transaction in your own words.', 'Ej: hoy gasté 10 mil en Open25': 'Example: today I spent 10 thousand at Open25', 'Registrar movimiento por voz': 'Record transaction by voice', 'Escribí o dictá el movimiento que querés registrar.': 'Write or dictate the transaction you want to record.', 'No pude reconocer el monto. Probá, por ejemplo: “hoy gasté 10 mil en Open25”.': 'I could not recognize the amount. Try, for example: “today I spent 10 thousand at Open25”.', 'No se pudo guardar el movimiento.': 'The transaction could not be saved.',
  'Ef+ (Efectivo)': 'Cash in', 'Ef- (Efectivo)': 'Cash out', 'Moneda': 'Currency', 'Cotización a ARS': 'ARS exchange rate', 'Categoría de detalle': 'Detail category', 'No modifica gastos, ingresos ni patrimonio.': 'It does not affect expenses, income, or net worth.',
  'Historial de movimientos': 'Transaction history', 'Buscar movimientos': 'Search transactions', 'Todos los tipos': 'All types', 'Monedas': 'Currencies', 'Todas las cuentas': 'All accounts', 'Tipo': 'Type', 'Detalle': 'Details', 'Cuenta': 'Account', 'Cargando movimientos…': 'Loading transactions…', 'No hay movimientos con esos filtros.': 'No transactions match these filters.', 'Modificar movimiento': 'Edit transaction', 'Editá los datos y presioná Guardar cambios.': 'Edit the details and press Save changes.', 'Motivo / descripción': 'Reason / description', 'Categoría / detalle': 'Category / detail', 'Enviar a la papelera': 'Move to bin', 'Eliminar movimientos seleccionados': 'Delete selected transactions', 'movimientos a la papelera?': 'transactions to the bin?', 'Enviar': 'Move', 'Guardando…': 'Saving…', 'Moviendo…': 'Moving…', 'Seleccionar todo': 'Select all', 'Quitar selección': 'Clear selection',
  'Gastos fijos': 'Recurring expenses', 'Agregar gasto fijo': 'Add recurring expense', 'Guardar gasto fijo': 'Save recurring expense', 'Pagar': 'Pay', 'Los préstamos de una misma persona se agrupan. Abrí cada grupo para consultar el detalle.': 'Loans to the same person are grouped. Open each group to view the details.', 'Suma de todos los préstamos pendientes': 'Sum of all outstanding loans', 'Todavía no registraste préstamos.': 'You have not recorded any loans yet.', 'Ahorros': 'Savings', 'Ahorros del mes seleccionado. Podés ocultar esta sección desde Configuración.': 'Savings for the selected month. You can hide this section in Settings.', 'No hay ahorros registrados este mes.': 'No savings recorded this month.', 'Accesos directos · clic derecho para editar': 'Shortcuts · right-click to edit', 'Soporte: gefisupport@gmail.com': 'Support: gefisupport@gmail.com',
  'Modificar acceso directo': 'Edit shortcut', 'El nombre es opcional; la URL es obligatoria.': 'The name is optional; the URL is required.', 'Nombre': 'Name', 'URL': 'URL', 'Eliminar acceso': 'Delete shortcut', 'Eliminar acceso directo': 'Delete shortcut', 'Sí, eliminar': 'Yes, delete', 'Completá los datos y guardá el gasto desde la página.': 'Complete the details and save the expense on this page.',
  'Sección de ahorros': 'Savings section', 'Mostrar los ahorros en la pantalla principal.': 'Show savings on the home screen.', 'Ajustá un total de la pantalla principal. La diferencia quedará registrada como un movimiento.': 'Adjust a total on the home screen. The difference will be recorded as a transaction.', 'Dinero en cuenta': 'Money in accounts', 'Inversiones del mes': 'Monthly investments', 'Actual:': 'Current:', 'Banco': 'Bank', 'Billetera': 'Wallet', 'No hay cuentas configuradas.': 'No accounts configured.', 'La URL es obligatoria; el nombre es opcional.': 'The URL is required; the name is optional.', 'Los movimientos se eliminan definitivamente después de 30 días.': 'Transactions are permanently deleted after 30 days.', 'La papelera está vacía.': 'The bin is empty.',
  'Estás sin conexión. Podés seguir usando GeFi: los cambios se sincronizarán cuando vuelva Internet.': 'You are offline. You can keep using GeFi: changes will sync when Internet returns.',
  'Buenos días': 'Good morning', 'Buenas tardes': 'Good afternoon', 'Buenas noches': 'Good evening', 'General': 'General', 'Alimentos': 'Food', 'Transporte': 'Transport', 'Salud': 'Health', 'Educación': 'Education', 'Hogar': 'Home', 'Ocio': 'Leisure', 'Trabajo': 'Work'
};

const reverse = Object.fromEntries(Object.entries(phrases).map(([es, en]) => [en, es]));

function translateText(value: string, language: Language) {
  const dictionary = language === 'en' ? phrases : reverse;
  const leading = value.match(/^\s*/)?.[0] || '', trailing = value.match(/\s*$/)?.[0] || '';
  const middle = value.slice(leading.length, value.length - trailing.length);
  return `${leading}${dictionary[middle] || middle}${trailing}`;
}

export function applyLanguage(language: Language, observe = language === 'en') {
  document.documentElement.lang = language;
  document.documentElement.dataset.language = language;
  const root = document.getElementById('root');
  if (!root) return () => undefined;
  const translate = (node: Node) => {
    if (node.nodeType === Node.TEXT_NODE) { const next = translateText(node.nodeValue || '', language); if (next !== node.nodeValue) node.nodeValue = next; }
    if (node.nodeType === Node.ELEMENT_NODE) {
      const element = node as HTMLElement;
      ['placeholder', 'title', 'aria-label'].forEach(attribute => {
        const value = element.getAttribute(attribute);
        if (value) { const next = translateText(value, language); if (next !== value) element.setAttribute(attribute, next); }
      });
      element.childNodes.forEach(translate);
    }
  };
  translate(root);
  if (!observe) return () => undefined;
  const observer = new MutationObserver(records => records.forEach(record => { if (record.type === 'characterData') translate(record.target); record.addedNodes.forEach(translate); }));
  observer.observe(root, { childList: true, characterData: true, subtree: true });
  return () => observer.disconnect();
}
